### ISSUE TITLE
Implement `glob.hasMagic`

### ISSUE THREAD

**Issue by evilebottnawi** [mrmlnc/fast-glob#105]
### Environment

  * OS Version: no matter
  * Node.js Version: no matter

### Actual behavior

Doesn't have `hasMagic` function.

### Expected behavior

Has `hasMagic` function. With same logic from https://github.com/isaacs/node-glob#globhasmagicpattern-options. Why? Allow full migrate from `node-glob` to `fast-glob`

### Steps to reproduce

not required

### Code sample

not required

Thanks!

**Comment by sindresorhus** [comment]
Would be useful if you could support multiple patterns here, in contrast to `node-glob`, so we can just depend on your implementation [in `globby`](https://github.com/sindresorhus/globby/blob/c16058c88afaa77f99c922a8682053fc661adcf3/index.js#L124-L126).

**Comment by mrmlnc** [comment]
@evilebottnawi,

Right now, I'm working on a different functionality that allows me to reduce the File System time by 10-20%.

I will come back to this issue later (in the next week, as I think).

**Comment by Qix-** [comment]
@mrmlnc It's been a few weeks... 🙃 ping?

**Comment by mrmlnc** [comment]
Sorry, I moved this issue to the milestones `3.0.0`. Right now I work on performance issues.

**Comment by mrmlnc** [comment]
Will be available with `fast-glob@3.1.0`.
