### ISSUE TITLE
[proposal] Ability to provide a provider for the File System

### ISSUE THREAD

**Issue by evilebottnawi** [mrmlnc/fast-glob#106]
Sorry for removed issue template. But looks irrelevant to question/rfc.

**Problem**: run `fast-glob` in non node env (i.e. browser/electron and etc).

**Why**: I contribute `webpack` and we have `webpack` bundle for run his in browser. For better zero configuration we want implement auto remove `dist` directory before each build (https://github.com/webpack/webpack/pull/7215). We use `del` package based on `globby` (i think `del` upgrade to latest globby in near future). `globby` use `fast-glob` in lastest version. But `fast-glob` use node `fs` module and it is and this makes the plugin not working in other environments.

**Solutions**: 

- Provide option/API to replace `fs` on own implementation (in `webpack` we have `outputFileSystem` which implement `fs` interface for other env).
- Create separate bundles for each env (looks difficult and overhead).

**Additional benefits**:
- Allow to implement playground with `fast-glob`.
- Allow to implement glob as filter in browser file managers.

What do you think about this?

**Comment by mrmlnc** [comment]
Hello, @evilebottnawi,

I think we can do it easily (relatively). We can change File System provider in the `readdir-enhanced` package (https://github.com/BigstickCarpet/readdir-enhanced/pull/10). Unfortunately, this will not work for static patterns, as it uses a different implementation for work with File System.

I'm currently working on a set of packages to work with the File System (@nodelib). In the future, I plan to replace the `readdir-enhanced` package with my own. I can think of a way to make it possible to provide your own adapter to work with the File System.

But how does it work in the old version of `globby`? The `globby@7` package uses `node-glob`, which also uses the FS module.

**Comment by evilebottnawi** [comment]
@mrmlnc don't worry about other packages and using `fs`, i will create issue, when re solve this here, because `fast-glob` in core package. Also i think `del` upgrade `globby` in near future. 

Option for own implementation file system will be enough. Maybe i can help you with this to faster solution?

**Comment by evilebottnawi** [comment]
In any case, thanks for accepting this issue and not just closing it with an answer won't fix

**Comment by evilebottnawi** [comment]
@mrmlnc Any news? Still need this feature :+1:

**Comment by mrmlnc** [comment]
I'm sorry I didn't answer sooner. I plan to add this feature in version [`3.0.0`](https://github.com/mrmlnc/fast-glob/milestone/1).

Also I have one question for you. Can you show a package that provides a way to replace methods for work with File System?

Because I can't concoct solution better rather than:

* https://github.com/nodelib/nodelib/blob/master/packages/fs/fs.stat/src/adapters/fs.ts

But in this case we have `import * as fs from 'fs'`.

**Comment by evilebottnawi** [comment]
@mrmlnc We want to use this package for `CleanerWebpackPlugin`, we have `memory-fs` in watch mode, so we need support to set any `fs` (yep we keep compatibility with original `fs`)

**Comment by mrmlnc** [comment]
This issue will be solved with release `fast-glob@3` where we introduce the `fs` option. You can check release issue #181.
