### ISSUE TITLE
Question about ignore patterns

### ISSUE THREAD

**Issue by keenwon** [mrmlnc/fast-glob#107]
### Environment

  * OS Version: Manjaro Linux x86_64 ( 4.14.39-1-MANJARO )
  * Node.js Version: v9.7.1

### Steps to reproduce & Code sample

src directory

```.
├── a.js
└── lib
    └── b.js
```

```js
const fg = require('fast-glob');
const glob = require('glob');

const files = 'src/**/*';
const ignore = ['src/lib/*'];

const fileList1 = fg.sync(files, {
  cwd: '/test',
  ignore,
  onlyFiles: true,
  absolute: true
});

const fileList2 = glob.sync(files, {
  cwd: '/test',
  ignore,
  nodir: true,
  absolute: true
});


console.log('fast-glob:');
console.log(fileList1);
console.log('glob:');
console.log(fileList2);

/**
fast-glob:
[ '/test/src/a.js',
  '/test/src/lib/b.js' ]
glob:
[ '/test/src/a.js' ]
*/
```

### Actual behavior

match [ '/test/src/a.js', '/test/src/lib/b.js' ]

### Expected behavior
match [ '/test/src/a.js' ]

**Comment by mrmlnc** [comment]
Looks like a bug! Thanks for report 🌮

**Comment by mrmlnc** [comment]
A little bit about how this happened.

In the [`convertPatternGroupsToTasks`](https://github.com/mrmlnc/fast-glob/blob/master/src/managers/tasks.ts#L88) function we try to find all negative patterns that starts with `base` path of each positive pattern. But in this case the positive pattern has a `base` path: `/test/src`. At the same time, the negative pattern has a `base` path: `/test/src/lib`.

**Comment by mrmlnc** [comment]
I will publish a fix to this issue today (https://github.com/mrmlnc/fast-glob/issues/109).
