### ISSUE TITLE
File not being captured with valid glob pattern

### ISSUE THREAD

**Issue by alan-agius4** [mrmlnc/fast-glob#11]
I have an issue that if my glob pattern is

`src/**/*.html`

And the file is directly under `src/index.html` it is not being captured.

Code: 
`return sync("src/**/*.html", { bashNative: [] });`

My OS is OS Sierra.

**Comment by mrmlnc** [comment]
Hello, @alan-agius4,

This is works fine in macOS Sierra 10.12.5. May be you have some options or symlink?

![fast-glob](https://user-images.githubusercontent.com/7034281/26896045-3abedd50-4bcc-11e7-90b2-1018540ffce2.png)
