### ISSUE TITLE
Can not find anything if the glob pattern contains brace(s)

### ISSUE THREAD

**Issue by tmcdos** [mrmlnc/fast-glob#111]
### Environment

  * OS Version: Windows 7 x64 SP1
  * Node.js Version: 8.11.2
  * fastGlob Version: 2.2.2

### Actual behavior
Unable to find anything when the glob pattern contains braces.

### Expected behavior
Must properly escape the glob pattern so that symbols which have special meaning do not interfere with the matching tests.

### Steps to reproduce

  1. Create a file named "d:\WORK\Arik Liber (therapists)\code\src\user\Messages.vue"

### Code sample

```js
const globby = require("globby"); 

const fileList = 'd:\\WORK\\Arik Liber (therapists)\\code\\src\\**\\*.vue';
const globbyOptions = {
  ignore:
  [
    '!**/node_modules/**',
    '!**/bower_components/**'
  ],
  expandDirectories: true
};
var list = globby(fileList, globbyOptions)
    .then(filePaths => { return filePaths; })
    .then((f) => console.log(f));

```

**Comment by tmcdos** [comment]
I think I've made a mistake. Seems like the problem is with the IGNORE patterns - if I remove the exclamation mark it finds files even if the folder name contains braces. Those **ignore** patterns actually come from the new Vue CLI 3.0 in their dynamic Webpack configuration - I will have to make further investigation and probably file an issue there.

You should probably close this issue.

**Comment by mrmlnc** [comment]
If the problem still reproduces – we can reopen the issue.

**Comment by tmcdos** [comment]
I made a simple test and the issue is apparently with `fastGlob` but the trick with `{ extension: false }` did solve it. The following code returns empty resultset without the trick. Probably should be mentioned in the documentation.

```javascript
const fastGlob = require('fast-glob');
fastGlob('z:\\x (y)\\**\\*.vue', { expandDirectories: true }).then(paths => console.log(paths));
```
