### ISSUE TITLE
Absolute ignore paths only work against absolute globs

### ISSUE THREAD

**Issue by davidtheclark** [mrmlnc/fast-glob#113]
### Environment

Node 8.
fast-glob v2.2.2

### Actual behavior

I have `format.js` in the same directory as this script.

```js
fastGlob('format.js', {
  ignore: [path.join(__dirname, '**')],
  cwd: __dirname
}).then(results => {
  console.log(results); // ['format.js']
});

fastGlob(path.join(__dirname, 'format.js'), {
  ignore: [path.join(__dirname, '**')],
  cwd: __dirname
}).then(results => {
  console.log(results); // []
});
```

### Expected behavior

I expect that absolute `ignore` paths will work against non-absolute globs. Instead, it seems like I need an absolute glob for an absolute `ignore` path to work.

I think I can work around this for now by making both globs and `ignore` paths relative to what I pass in as `cwd`.

**Comment by mrmlnc** [comment]
Will be shipped at #36.
