### ISSUE TITLE
glob misses folders on some architectures 

### ISSUE THREAD

**Issue by cdaringe** [mrmlnc/fast-glob#115]
originally filed at  https://github.com/sindresorhus/globby/issues/89

### Environment

  * OS Version: centos 7, 3.10.0-693.21.1.el7.x86_64
  * Node.js Version: 10.8.0

### Actual behavior

produces empty array

### Expected behavior

produces populated array

### Steps to reproduce

- create dir w/ folders
- run glob as below

```
$ ll /home/cdieringer/src/proj/packages/
total 28
drwxrwxr-x.  7 cdieringer cdieringer 4096 Aug  9 13:51 ./
drwxrwxr-x. 10 cdieringer cdieringer 4096 Aug  9 13:52 ../
drwxrwxr-x.  8 cdieringer cdieringer 4096 Aug  9 13:53 api/
drwxrwxr-x.  5 cdieringer cdieringer 4096 Aug  9 13:52 common/
drwxrwxr-x.  7 cdieringer cdieringer 4096 Aug  9 13:52 e2e/
drwxrwxr-x.  8 cdieringer cdieringer 4096 Aug  9 13:53 ui/

$ node
> const fg = require('fast-glob')
undefined
> fg.sync([` /home/cdieringer/src/proj/packages/*`])
[]
```

**Comment by mrmlnc** [comment]
In your example, I can see that there are several subdirectories inside some directory.

By default, this package returns only files. You can disable this behavior using the [`onlyFiles`](https://github.com/mrmlnc/fast-glob#onlyfiles) option.
