### ISSUE TITLE
markDirectories doesn't work with absolute:true given a relative path

### ISSUE THREAD

**Issue by rijnhard** [mrmlnc/fast-glob#121]
### Actual behavior
markDirectories does not work when the glob is a relative path and absolute is set to true. Digging into the code it looks like the order of operations of ` Reader.prototype.transform` is incorrect causing it to undo the marked directories/

```
/full/path/test/things/a
/full/path/test/things/b
/full/path/test/things/c
```

### Expected behavior
```
/full/path/test/things/a/
/full/path/test/things/b/
/full/path/test/things/c/
```

### Code sample

```js
import fglob from 'fast-glob'; 

const relativeGlob = 'test/fixtures/*/';

async function test() {
	const list = await fglob(relativeGlob, { absolute : true, onlyDirectories: true, markDirectories:true });

	console.info(list);
}

test();
```

**Comment by mrmlnc** [comment]
Will be shipped at #136.
