### ISSUE TITLE
dot:true doesn't work

### ISSUE THREAD

**Issue by koalaylj** [mrmlnc/fast-glob#123]
### Environment

  * OS Version: MacOS 10.13.6
  * Electron: 3.0.4
  * fast-glob:2.2.3

### Actual behavior
```glob(['/user/abc/**/*.png'],{dot:true})``` cannot match `..png` file

### Expected behavior
should match `..png`file

**Comment by mrmlnc** [comment]
I understand correctly that the file literally has a name `..png`?

**Comment by koalaylj** [comment]
> I understand correctly that the file literally has a name `..png`?

yes  the file name is `..png`(double leading dots)

**Comment by mrmlnc** [comment]
Closing in favor of issue to use `micromatch@4` (#154). This issue will be fixed with release `fast-glob@3`. You can check release issue #181.
