### ISSUE TITLE
[Feature Request] provide a test function to see if a path is matched by target pattern(s)

### ISSUE THREAD

**Issue by e-cloud** [mrmlnc/fast-glob#131]
Assume the future method is called `isMatch(filePath, patterns, options)`

then I want to achieve the follow:

```
fastGlob.isMatch('./package.json', ['src/*.json'])
// return false
```

Note: A hidden requirement is I want to keep the ability to constraint the patterns under specify scope (aka `cwd`). Otherwise i could use `micromatch` directly.

guided from https://github.com/sindresorhus/globby/issues/93

**Comment by mrmlnc** [comment]
I correctly understand that under the `options` argument you understand options for FastGlob?

**Comment by e-cloud** [comment]
@mrmlnc sorry, I don't understand your words. In the provided example I just use the default options.

**Comment by mrmlnc** [comment]
It is not planned to implement, as this functionality is outside the scope of this package. This package provides functionality for searching entries by glob patterns and utilities for preparing these glob patterns.

The requested functionality directly relates to matching a mask to a path. You can use micromatch or any other analog for this purpose.
