### ISSUE TITLE
An entry that should be included is ignored

### ISSUE THREAD

**Issue by zkochan** [mrmlnc/fast-glob#138]
### Environment

  * OS Version: Linux
  * Node.js Version: 10.12.0

### Actual behavior

An entry is ignored even though it should not be matched by any ignore patterns

### Expected behavior

`'packages/foo-foo/package.json'` is not ignored by the ignore pattern: `!**/foo/**/package.json`

### Code sample

You can clone [this repo](https://github.com/zkochan/fast-glob-issue) and run `npm install && node index.js`

```js
'use strict'
const glob = require('fast-glob')

glob([
  '**/packages/**/package.json',
  '!**/foo/**/package.json',
])
.then((entries) => console.log(entries))
```

**Comment by mrmlnc** [comment]
Thanks for issue. I will look into it soon.

**Comment by zkochan** [comment]
One thing I just noticed. If I change the ignore pattern to `'!**/foo/**` then it works correctly.

but both versions work with `glob`

**Comment by mrmlnc** [comment]
The previous comment is incorrect.

The `micromatch` package converts the pattern to RegExp:

```
/^(?:(?:\.[\\\/](?=.))?(?:(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/])?foo[\\\/]?(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/]package\.json(?:[\\\/]|$))$/
```

And…

```js
/^(?:(?:\.[\\\/](?=.))?(?:(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/])?foo[\\\/]?(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/]package\.json(?:[\\\/]|$))$/.test('packages/foo-foo/package.json')

true
```

**Comment by mrmlnc** [comment]
I'll take a look at the problem in the `micromatch` package.

**Comment by mrmlnc** [comment]
Closing in favor of issue to use `micromatch@4` (#154). After upgrade:

```js
[ 'packages/foo-foo/package.json' ]
```

This issue will be fixed with release `fast-glob@3`. You can check release issue #181.
