### ISSUE TITLE
latest version 2.2.5 is broken and throws errors

### ISSUE THREAD

**Issue by shlomitc** [mrmlnc/fast-glob#146]
### Environment

  * OS Version: MacOS 10.12.6
  * Node.js Version: 8.9.1

### Actual behavior
Running some command that uses `fast-glob` as part of `globby` is throwing following error
```bash
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/Users/shlomitc/WebstormProjects/yoshi-with-base-ui/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/Users/shlomitc/WebstormProjects/yoshi-with-base-ui/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /Users/shlomitc/WebstormProjects/yoshi-with-base-ui/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /Users/shlomitc/WebstormProjects/yoshi-with-base-ui/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
    at <anonymous>
```

### Expected behavior
not to break. previous version worked perfectly

### Steps to reproduce
might be a bit hard to reproduce as it's part of a build tool I'm using

### Code sample
don't have one

**Comment by alexander-schranz** [comment]
Does happen for example when running `stylelint scss/**/*.scss`

**Comment by dodozhang21** [comment]
we have the same issue

**Comment by iameli** [comment]
duplicate of #144

**Comment by shlomitc** [comment]
@iameli thanks, closing
