### ISSUE TITLE
End of Node.js 4/6 support

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#152]
With release `fast-glob@3` we will remove support for Node.js below 6. Also I want to remove support for Node.js below 8, but… even after the end-of-life (April 2019), this version will have users.

With Node.js 8 we can use native Async/Await for better performance and some sugar for streams.

**Comment by mrmlnc** [comment]
Maybe try WebAssembly?

**Comment by sindresorhus** [comment]
FWIW, I plan to move `globby` to target Node.js 8 in April. I think you should just move to Node.js 8. It will simplify maintenance.
