### ISSUE TITLE
Move to micromatch@4 or picomatch

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#154]
We have a big problem related to package `require` time (#92). This issue is related to micromatch, which has a very large number of dependencies.

About micromatch@4:

* https://github.com/micromatch/micromatch/issues/137

Also micromatch/picomatch has a problem: 

* https://github.com/micromatch/micromatch/issues/140
* https://github.com/mrmlnc/fast-glob/issues/159
* https://github.com/mrmlnc/fast-glob/issues/160

**Comment by mrmlnc** [comment]
https://github.com/terkelg/globrex to compare performance and minimatch

**Comment by jonschlinkert** [comment]
@mrmlnc fwiw I just pushed up picomatch v2.0: https://github.com/micromatch/picomatch/tree/dev. I also got it completely ported to micromatch, and I'm now working on docs.

**Comment by mrmlnc** [comment]
Plan for integration with the new version:

* [ ] Create @types/picomatch
* [ ] Update @types/micromatch
* [ ] Use the new version of micromatch
