### ISSUE TITLE
Paths not resolved

### ISSUE THREAD

**Issue by stevenvachon** [mrmlnc/fast-glob#157]
### Environment

  * OS Version macOS 10.14.2
  * Node.js Version: 10.15.0

### Actual behavior
Paths are not resolved, with and without enabling the `absolute` option.

### Expected behavior
Paths should have "." and ".." instances resolved.

### Code sample
```js
const paths = await fg('/project/temp/../*.js', {absolute: true});

console.log(paths[0]); //-> '/project/temp/../file.js'
```

**Comment by mrmlnc** [comment]
This issue will be fixed with release `fast-glob@2.2.7`. You can check release issue #180.
