### ISSUE TITLE
Difference behavior for dot files on windows and linux

### ISSUE THREAD

**Issue by evilebottnawi** [mrmlnc/fast-glob#159]
### Environment

  * OS Version: windows/linux
  * Node.js Version: 8.15.0

### Actual behavior

We have file `directory/.dottedfile`

pattern - `{file.txt,noextension,directory/**/*}`

On linux - file founded
On windows - no

https://ci.appveyor.com/project/webpack-contrib/copy-webpack-plugin/builds/22457587/job/y5320ckr1fvs6r67

### Expected behavior

Founded on linux and windows, or provide documentation why it is doesn't work and/or how can be fixed

### Steps to reproduce

Below

### Code sample

```js
fg(['{file.txt,noextension,directory/**/*}'], { dot: true }).then((entries) => console.log(entries));
```

**Comment by mrmlnc** [comment]
It looks weird. Does not work on Windows 10 and WSL (Ubuntu). Also does not work with the `minimach` package.

This a RegExp for `Entry` filter:

```js
/^(?:(?:\.[\\\/](?=.))?(?:bench\.js|directory[\\\/](?:(?!(?:[\\\/]|^)(?:\.{1,2})($|[\\\/]))(?!\.{2}).)*?[\\\/](?!(?:^|[\\\/])\.{1,2}(?:$|[\\\/]))(?!(\.{2}|\.[\\\/]))(?=.)[^\\\/]*?)(?:[\\\/]|$))$/
```

The entries in my directory:

```
bench.js
directory/.dotted
```

And…

```
const re = /^(?:(?:\.[\\\/](?=.))?(?:bench\.js|directory[\\\/](?:(?!(?:[\\\/]|^)(?:\.{1,2})($|[\\\/]))(?!\.{2}).)*?[\\\/](?!(?:^|[\\\/])\.{1,2}(?:$|[\\\/]))(?!(\.{2}|\.[\\\/]))(?=.)[^\\\/]*?)(?:[\\\/]|$))$/;

re.test('bench.js'); // → true
re.test('directory/.dotted'); // → false
```

**Comment by mrmlnc** [comment]
As a temporary solution, you can divide the pattern into several:

```js
const entries = fg.sync(['bench.js', 'directory/**/*'], {
    dot: true
});
```

**Comment by evilebottnawi** [comment]
@mrmlnc thanks, we want to migrate `copy-webpack-plugin` (https://www.npmjs.com/package/copy-webpack-plugin) on last globby (uses `fat-glob`) and can't use this workaround, unfortunately we cannot migrate due to this problem, also i find something strange this `(` and `)` characters you can see all failed tests https://ci.appveyor.com/project/webpack-contrib/copy-webpack-plugin/builds/22457587/job/y5320ckr1fvs6r67 (on old `globby` with `node-glob` all tests passed)

**Comment by jonschlinkert** [comment]
> also i find something strange this `(` and `)` characters you can see all failed tests https://ci.appveyor.com/project/webpack-contrib/copy-webpack-plugin/builds/22457587/job/y5320ckr1fvs6r67 (on old `globby` with `node-glob` all tests passed)

FWIW, the tests passed with node-glob because node-glob can't handle non-extglob parenthesis and so it just escapes everything, resulting in `\\(`. It's not technically "working", it's just coincidental that your pattern happened to work, as the escaping often results in nothing matching at all. 

To use parens with micromatch, you can either use a valid extglob, like `+(foo|bar)`, or escape the parens with backslashes, like `\\(`. 

Happy to help if you still have questions.

**Comment by evilebottnawi** [comment]
@jonschlinkert can you clarify with examples, thanks

**Comment by jonschlinkert** [comment]
> unfortunately we cannot migrate due to this problem, also i find something strange this ( and ) characters you can see all failed tests

The pattern `(special-file).txt` should be `\\(special-file\\).txt`. 

I think that was the only failing pattern, correct? 

The reason node-glob matched before is that minimatch assumes that `(` and `)` should always be matched literally and adds `\\` before all parentheses.

**Comment by jonschlinkert** [comment]
@evilebottnawi @mrmlnc 

FWIW I'm definitely open to changing the default behavior in micromatch/picomatch to assume that `(` and `)` should always be matched literally. We can require the user to enable regex-like behavior using options. We can at least get a discussion going if you think it makes sense.

**Comment by mrmlnc** [comment]
Sorry guys, I don't have free time right now.  I'll be back as soon as I can. Add a record to the ToDo.

**Comment by jonschlinkert** [comment]
No worries take your time!

**Comment by mrmlnc** [comment]
I suggest we relocate discussion to the Picomatch repository. It seems that in this ticket we had to talk about curly braces.

https://github.com/micromatch/picomatch/issues/7

**Comment by mrmlnc** [comment]
The original problem is fixed after migration from `micromatch@3` to `micromatch@4`.

https://github.com/mrmlnc/fast-glob/issues/154
