### ISSUE TITLE
Error: UNKNOWN: unknown error, lstat on WSL symbolic links

### ISSUE THREAD

**Issue by bmewburn** [mrmlnc/fast-glob#161]
Thanks for your effort on this project. I'm using fast-glob in a PHP language server and am getting reports from users about lstat errors. Most of these users are on Windows and are using WSL, though a minority appear not to be using WSL.

This is the issue containing most of the information:
https://github.com/bmewburn/vscode-intelephense/issues/260 

This may also be useful:
https://github.com/Microsoft/WSL/issues/1524

I'm not a Windows user myself but will try and add some further info later.

### Environment

 Windows

### Actual behavior
`Error: UNKNOWN: unknown error, lstat 'e:\firma\fbpopular\public\storage'`

### Expected behavior
No error.

### Steps to reproduce

  1. Try and find files in a dir structure that contains symbolic links on windows WSL

**Comment by mrmlnc** [comment]
Hello, @bmewburn,

Thanks for issue. I correctly understand that  asymbolic link was created under WSL and trying to use it under Windows?

Also a few leading questions:

0. How you create symbolic link under WSL? `ln -s SOURCE TARGET`?
1. You can call `fs.lstatSync` under WSL in the Node.js REPL? Also under Windows (file output, please)?
2. You can call `(Get-Item PATH_TO_SYMBOLIC_LINK_IN_WSL_DIRECTORY).Target` in the PowerShell?
3. WSL is Ubuntu from https://github.com/bmewburn/vscode-intelephense/issues/260?

We need diagnostics from the user who has problems. Unfortunately, without `lstat` this package won't work.

**Comment by bmewburn** [comment]
Thanks @mrmlnc . Will try to find time to debug further. I dont think it's just WSL, this user is reporting that it's NTFS junction points https://github.com/bmewburn/vscode-intelephense/issues/461 .

**Comment by mrmlnc** [comment]
I think this behavior is not relevant to the `readdir-enhanced` package. You can provide any reproduce steps? Maybe `gti` repository or just steps? :)

**Comment by mrmlnc** [comment]
Reproduce steps:

```
wsl
touch a.txt
ln -s a.txt b.txt
exit
node
require('../fast-glob').sync('*')
```

**Comment by mrmlnc** [comment]
So, after research: the `node-glob` package just ignore error from `lstat` call.

**Comment by mrmlnc** [comment]
Unfortunately, the correct behavior is only guaranteed for Node.js 10.10+. For the correct operation of the package requires information about what the file in front of us: symbolic link, file or something else. We cannot ignore the `lstat` error, otherwise, there will be inconsistency between modes: `string`, `dirent` and `stat`.

So, right now VS Code build with Node.js 10.2.0. The next update was delayed (https://github.com/microsoft/vscode/issues/61787).

I will describe this behavior in the documentation.
