### ISSUE TITLE
Allow to readd ignored files

### ISSUE THREAD

**Issue by sebbi08** [mrmlnc/fast-glob#162]
### Environment

  * OS Version: MAC OSX
  * Node.js Version: v10.15.2

### Actual behavior
it removes everything in the resource folder

### Expected behavior
the patterns after the first ignore pattern should be readding the files again.

### Code sample

```js
fast-glob.sync([
    "**/*.*",
    "!resources/**/*.*",
    "resources/sap-ui-custom.js",
    "resources/myLib/**/themes/myTheme/**/*.{css,json}",
    "resources/myLib/**/assets/**/*.*",
    "resources/sap/**/themes/myTheme/**/*.{css,json}"
  ], {
         cwd: options.base,
         onlyFiles: true
})
```

or maybe there is a way to achieve this i am missing

**Comment by mrmlnc** [comment]
Hello, @sebbi08,

Thanks for issue. Unfortunately, the `fast-glob` package does not respect the order of patterns.

> This package does not respect the order of patterns. First, all the negative patterns are applied, and only then the positive patterns.

Does the `node-glob` package or any other tool (maybe Python, Rust, etc.) have this behavior?

Right now you can call the `fast-glob` package twice. The second call should be fast.

```ts
const first = [
    "**/*.*",
    "!resources/**/*.*",
];

const second = [
    "resources/sap-ui-custom.js",
    "resources/myLib/**/themes/myTheme/**/*.{css,json}",
    "resources/myLib/**/assets/**/*.*",
    "resources/sap/**/themes/myTheme/**/*.{css,json}"
];
```

**Comment by sebbi08** [comment]
na sadly node-glob ha no such function it just somthing i found in the [Grunt ](https://gruntjs.com/api/grunt.file#grunt.file.expand) file api can do somthing like this but i might have to do it your way

**Comment by mrmlnc** [comment]
This package will never respect the order of patterns (this is the basis of the work of this package). You can split patterns into multiple calls.
