### ISSUE TITLE
Leaked micromatch implementation behaviour

### ISSUE THREAD

**Issue by janat08** [mrmlnc/fast-glob#173]
### Environment

  * OS Version: ubuntu 19.04
  * Node.js Version: 10.15.3

I won't pretend to understand the issue. This manifests in downstream package: https://github.com/sindresorhus/globby/issues/97#issuecomment-467196294.

**Comment by jonschlinkert** [comment]
From the linked issue:

> fast-glob uses micromatch, which turns tmp\\**\\*.{md,tmp} into tmp/**/*.(md|tmp) using brace expansion. When noext is specified, literal parentheses get matched:

Micromatch explicitly does not convert `\\` to `/` in globs, as that is unsafe and could enable malicious regular expressions to be used.

**Comment by jonschlinkert** [comment]
related: 

- https://github.com/micromatch/micromatch/pull/142#issuecomment-478234378
- https://github.com/micromatch/picomatch/issues/7

**Comment by mrmlnc** [comment]
```

**Comment by mrmlnc** [comment]
Tasks:

```js
[
    {
        base: 'fixtures',
        dynamic: true,
        patterns: ['fixtures/**/*.{md,txt}'],
        positive: ['fixtures/**/*.{md,txt}'],
        negative: []
    }
]
```

Micromatch options:

```js
{
    dot: false,
    nobrace: false,
    noglobstar: false,
    noext: true,
    nocase: false,
    matchBase: false
}
```

## `micromatch@3`

Micromatch RegExp:

```js
/^(?:(?:\.[\\\/](?=.))?fixtures[\\\/]?\b(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/](?!\.)(?=.)[^\\\/]*?\.\(md|txt\)(?:[\\\/]|$))$/
```

When the `extension` option has `true` as value:

```
/^(?:(?:\.[\\\/](?=.))?fixtures[\\\/]?\b(?!\.)(?:(?!(?:[\\\/]|^)\.).)*?[\\\/](?!\.)(?=.)[^\\\/]*?\.(?:md|txt)(?:[\\\/]|$))$/
```

## `micromatch@4`

```js
{
	dot: false,
	nobrace: false,
	noglobstar: false,
	noext: true,
	nocase: false,
	matchBase: false
}
```

RegExp:

```js
/^(?:fixtures(?:[\\\/](?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)[\\\/]|[\\\/]|$)(?!\.)(?=.)[^\\\/]*?\.(md|txt))$/
```

**Comment by mrmlnc** [comment]
Closing in favor of issue to use `micromatch@4` (#154). This issue will be fixed with release `fast-glob@3`.
