### ISSUE TITLE
Document behaviour with "dot" folders

### ISSUE THREAD

**Issue by rprieto** [mrmlnc/fast-glob#19]
First thanks a lot for this package. It's much faster than `node-glob` with a much lower memory usage! 

One issue I faced while migrating is that `node-glob` skips all folders that start with a dot, probably in case they're not traversable. `fast-glob` doesn't skip them which can lead to permission issues like `Error: EACCES: permission denied, scandir 'test/.foo'` (fails the whole scan).

This can be fixed using:

```
fastGlob(pattern, {
  deep: stats => stats.path.charAt(0) !== '.'
})
```

Maybe you could document this in the README in the `Compatible with node-glob` section?

**Comment by mrmlnc** [comment]
Hello, @rprieto,

Thanks for you issue. I am really glad to see that my package may be useful not only me ❤️ 

Also, sorry for the long response. I've been super busy for the past several weeks and haven't had any spare time to look into this.

But… i'm here 🎉 

Well, in the `fast-glob@2` was introduced new option `dot` that fully compatible with node-glob. I also added a [comparison table](https://github.com/mrmlnc/fast-glob#compatible-with-node-glob). The new version of **fast-glob** will be released very soon.

**Comment by rprieto** [comment]
Hi, no problem at all! Looking forward to the new version.
