### ISSUE TITLE
Show invalid symlinks

### ISSUE THREAD

**Issue by vjpr** [mrmlnc/fast-glob#207]
Is there a way to have a symlink show up if the symlink is pointing to a non-existent file? I couldn't manage to figure it out.

**Comment by vjpr** [comment]
Had to use `onlyFiles: false`.

**Comment by mrmlnc** [comment]
Hi, @vjpr,

Yeap. You can use [`onlyFiles`](https://github.com/mrmlnc/fast-glob#onlyfiles) or [`throwErrorOnBrokenSymbolicLink`](https://github.com/mrmlnc/fast-glob#throwerroronbrokensymboliclink) options.
