### ISSUE TITLE
Non-existing directories in globbing pattern (`ENOENT`) throw errors

### ISSUE THREAD

**Issue by ehmicky** [mrmlnc/fast-glob#211]
### Environment

  * OS Version: Ubuntu `19.04`
  * Node.js Version: `12.4.0`

### Actual behavior

Using `fast-glob@3.0.2`:

```
> await fastGlob('doesNotExist/*')
Thrown:
[Error: ENOENT: no such file or directory, scandir '/home/myPackage/doesNotExist'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/myPackage/doesNotExist'
}
```

### Expected behavior

What `fast-glob@2.2.7` used to do:

```
> await fastGlob('doesNotExist/*')
[]
```

### Steps to reproduce

See above.

### Code sample

See above.

**Comment by mrmlnc** [comment]
Already fixed in the `master` branch. The release is planned in the near future.

**Comment by ehmicky** [comment]
Thanks @mrmlnc!
