### ISSUE TITLE
Absolute globs not working

### ISSUE THREAD

**Issue by tlrobinson** [mrmlnc/fast-glob#227]
### Environment

  * `fast-glob` Version: 3.0.4
  * OS Version: macOS 10.14.3
  * Node.js Version: v10.15.3

### Actual behavior

Absolute globs do not return any results.

### Expected behavior

They should.

### Steps to reproduce

Glob any pattern that starts with `/` you would expect to match at least one file.

### Code sample

```
> require("fast-glob").sync("/")
[]
> require("glob").sync("/")
[ '/' ]
```

**Comment by mrmlnc** [comment]
Hello, @tlrobinson,

You need to use the `onlyFiles` or `onlyDirectories` option. The `glob` package includes directories by default.

```js
const entries = fg.sync('/', {
	onlyFiles: false
});

console.dir(entries, { colors: true }); // false → ['/'] | true → []
```

**Comment by tlrobinson** [comment]
@mrmlnc Ah, thanks. I had also tried with `/dev/*` which are not files either.
