### ISSUE TITLE
End of Node.js 8 & 10 & 12 & 14 support

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#235]
In the new version (`4.0.0`), we want to exclude version node.js 8, 10, 12, 14 from support.

We will support the following versions another year:

* 16.0.0+

Node.js releases lifecycle:

https://nodejs.org/en/about/releases/
https://nodejs.org/en/about/releases/
https://github.com/nodelib/nodelib/issues/48

**Comment by mrmlnc** [comment]
Another reason:

* https://github.com/mrmlnc/fast-glob/pull/301/files#diff-25d0892e632212bf426c5e5090107e8a21098d1ea1178c972f7cf75ae0b323fcR42

**Comment by mrmlnc** [comment]
Also:

https://github.com/mrmlnc/fast-glob/blob/b9f74dd8aa9d54ad674f9f843d1747dcc12c762d/src/readers/async.ts#L27-L32

**Comment by sindresorhus** [comment]
Node.js 12 is no longer supported either. Maybe time to do a major release?

**Comment by mrmlnc** [comment]
It is time!

https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/

**Comment by mrmlnc** [comment]
The `main` branch now requires Node.js 16.14.0 and above.
