### ISSUE TITLE
Cannot read property 'absolute' of null

### ISSUE THREAD

**Issue by jjdotcc** [mrmlnc/fast-glob#236]
### Environment

  * OS Version: Windows Server 2019 Standard
  * Node.js Version: 10.16.0
  * fast-glob Version: Latest

When attempting to call fast-glob I get an exception

Cannot read property 'absolute' of null
    at new Settings (\node_modules\fast-glob\out\settings.js:18:54)

node_modules\fast-glob\out\settings.js:18
        this.absolute = this._getValue(this._options.absolute, false);

**Comment by mrmlnc** [comment]
How can I reproduce your problem on my machine?

**Comment by jjdotcc** [comment]
Actually it is not an issue. It was caused by slippery null 🤦‍♂
