### ISSUE TITLE
Doesn't match specific filepath on Windows

### ISSUE THREAD

**Issue by pvdlg** [mrmlnc/fast-glob#237]
### Environment

  * OS Version: Windows on Travis CI / Linux on Travis CI
  * Node.js Version: 12

### Actual behavior

The test code creates a file in the temp directory and try to glob it:
```js
const path = require('path');
const fg = require('fast-glob');
const glob = require('glob');
const {promisify} = require('util');
const {outputFile, access, F_OK} = require('fs-extra');

async function test() {
  const filepath = path.join('directory', 'file-name.txt');
  await outputFile(filepath, 'test file content', {encoding: 'utf8'});

  try {
    await access(filepath, F_OK);
    console.log(`File ${filepath} exists`);

    const result = await fg([filepath]);
    console.log('fast-glob result', result);

    const globResult = await promisify(glob)(filepath);
    console.log('node-glob result', globResult);

  } catch(error) {
    console.log(`File ${filepath} does not exists`)
  }
}

test().catch((error) => {
  console.log(error);
});
```

On Linux both `fast-glob` and `node-glob` find the file.
On Windows `node-glob` finds the file but `fast-glob` doesn't.

See the Travis run here: https://travis-ci.org/pvdlg/playground/builds/602472196

### Expected behavior
`fast-glob` should work both on Linux and Windows the same way and find file passed with an absolute path.

**Comment by mrmlnc** [comment]
The `fast-glob` package since `3.0.0` does not support backslashes as path separator.

```js
const filepath = path.join('directory', 'file-name.txt');
// directory\\file-name.txt
```

Release notes:

* https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0

> Only forward-slashes in glob expression. Previously, we convert all slashes to the forward-slashes, which did not allow the use of escaping. See pattern syntax section in the README.md file.

Documentation:

* https://github.com/mrmlnc/fast-glob#pattern-syntax
* https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows

**Comment by pvdlg** [comment]
My bad, I didn't realized that...
