### ISSUE TITLE
Add method to convert paths to globs

### ISSUE THREAD

**Issue by sindresorhus** [mrmlnc/fast-glob#240]
The change in [3.0.0](https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0) that changed it to only allow forward slash paths turned out to be a pain. Anywhere I use `fast-glob`, I now need to specially normalize paths on Windows.

Would be useful if `fast-glob` had a `.convertToGlob()` kinda method, with similar logic to https://github.com/sindresorhus/del/commit/01da91f548a318f33a82e9f09eb27f4e5c6cb94b#diff-168726dbe96b3ce427e7fedce31bb0bcR41-R53.

Maybe there could even be some kind of option to loosen `fast-glob`, when you don't need glob escaping, but do need to accept both file paths and globs, which is actually the majority of cases, at least for me.

**Comment by mrmlnc** [comment]
Fixed in the master by #392. Will be shipped with [`3.3.0`](https://github.com/mrmlnc/fast-glob/issues/396).
