### ISSUE TITLE
Typescript issues with lerna mono-repository

### ISSUE THREAD

**Issue by iamchathu** [mrmlnc/fast-glob#245]
### Environment

  * OS Version: … macOS X
  * Node.js Version: … v12.13.0 and node:lts docker image

### Actual behavior

```bash
tsc
node_modules/fast-glob/out/index.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/Workspace/project/packages/sub-project/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/Workspace/project/node_modules/@types/node/ts3.2/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~

node_modules/fast-glob/out/types/index.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/Workspace/project/packages/sub-project/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/Workspace/project/node_modules/@types/node/ts3.2/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />

```

### Expected behavior
Compile without issues.

### Steps to reproduce

  1. create lerna project with lerna init
  2. setup lerna with yarn npmClient
  3. enable yarn workspaces
  4. create a typescript package inside packages folder
  5. Add fast-glob as dependency
  6. Add @types/node as dev dependency
  5. Write some code using fast-glob
  7. Create another typescript package in packages folder
  8. Add @types/node as dev dependency
  9. Try to run `tsc` in first package

After many trials seems it works if I remove @types/node dependancy (which removes symlink in local node_modules folder), since it still has root node_modules with @types/node since other package is depend on it.

**Comment by mrmlnc** [comment]
Hello, @iamchathu,

The `fast-glob` package does not distribute any versions of the `@types/node` package. This package is installed separately if the user uses TS. The compiler itself tries to find this package. Looks like you have two or more versions of this package in your repository.

Unfortunately, I can't help you. The problem with code `TS4090` is a very popular and you can find solution by search (something like [this](https://www.google.com/search?q=ts4090+conflicting+definitions+for+%27node%27+found+at)).

**Comment by iamchathu** [comment]
@mrmlnc Thanks fro the quick reply. I actually did google and tried many solutions. There is no two versions but with Mono-repo setup it do hoist the dependancies to root and create symlinks in local node_modules folder. That's why it complaining and the issue was came recent update and it wasn't had any issues early with same setup.
