### ISSUE TITLE
escapePath() doesn't work properly

### ISSUE THREAD

**Issue by scylo** [mrmlnc/fast-glob#248]
### Environment

  * OS Version: VM Win 10
  * Node.js Version: v12.10.0

### Actual behavior
glob.sync("path/with/a (parethesis)/*") doesn't work
glob.sync(glob.escapePath("path/with/a (parethesis)/*")) doesn't work
glob.sync("path/with/a \(parethesis\)/\*") doesn't works
glob.sync("path/with/a \\\\(parethesis)/\\*") doesn't works

glob.sync("path/with/a \\\\(parethesis)/*") works
glob.sync("path/with/a \\\\(parethesis)/\*") works
glob.sync("path/with/a *parethesis*/\*") doesn't works

![image](https://user-images.githubusercontent.com/7854818/72375693-520cb380-36eb-11ea-8bbc-88ec6dff7466.png)

### Expected behavior
glob.sync(glob.escapePath("path/with/a (parethesis)/*")) should works

### Steps to reproduce
do a simple glob.sync() with some parenthesis in the name folder

### Code sample

```js
options = {
  cwd: "//VBOXSVR/Documents",
  caseSensitiveMatch: false,
  onlyDirectories: false,
  onlyFiles: false
}
glob.sync(glob.escapePath('ARQUIVOS - EMPRESAS/INNOVAFATTO (MATRIZ SP)/FISCAL/2019/12.2019/iss*'), options)
```

**Comment by mrmlnc** [comment]
Hello, @scylo,

The `escapePath` cannot be applied to the path on your screenshot because this is not a path, but a pattern (has `*`). This method cannot determine for you that you only need to escape the parentheses and not touch the asterisk.

The following example show how you can solve your problem:

```js
const fg = require('fast-glob');

const pattern = [
    // 'ARQUIVOS - EMPRESAS/INNOVAFATTO (MATRIZ SP)/FISCAL/2019/12.2019/iss', // will not work
    fg.escapePath('ARQUIVOS - EMPRESAS/INNOVAFATTO (MATRIZ SP)/FISCAL/2019/12.2019/iss'), // work
    '*'
].join('');

const entries = fg.sync(pattern);

console.dir(entries, { colors: true });

```

**Comment by mrmlnc** [comment]
Closed as outdated issue.
