### ISSUE TITLE
fast-glob@3.2.0 uses an outdated version of picomatch with Yarn

### ISSUE THREAD

**Issue by anilanar** [mrmlnc/fast-glob#253]
### Environment

  * OS Version: MacOS
  * Node.js Version: 12.14.0

There was a regression in https://github.com/dotansimha/graphql-code-generator and after investigating the issue, I've concluded that there's a regression in `fast-glob@3.2.0`.

You can see the original issue here, which has a reproduction in codesandbox: https://github.com/dotansimha/graphql-code-generator/issues/3512

The problem:

https://github.com/mrmlnc/fast-glob/blob/1757299eeec95c9e03bbf965a9f6903184e68a26/src/utils/pattern.ts#L106-L118

With `micromatch@4.0.2` (latest version), `info` doesn't seem to have a `parts` property.

**Comment by anilanar** [comment]
Could this be a further problem down the rabbit hole in `micromatch -> picomatch`?

**Comment by jonschlinkert** [comment]
@mrmlnc let me know if you need me to do something to fix this. I can push up a patch if you need me to and can give me guidance on what needs to be fixed, but I won't have much time to debug until Tuesday morning. 

Or ping me if you want me to add you to the repo and npm -- we've collaborated a lot over the past couple of years, I'd be happy to add you.

**Comment by mrmlnc** [comment]
Looks like we we got a combo.

Initial state:

```
fast-glob → micromatch@^4.0.2 → picomatch@^2.0.5
```

Something inside the `graphql-code-generator` also requires the `picomatch` version. But I can't see anywhere declaration with `~`.

To avoid this situation we need:

* [ ] Require `picomatch@^2.2.1` inside `micromatch`.
* [ ] Require `micromatch@4.x.x` inside `fast-glob`.

**Comment by ivan-kleshnin** [comment]
Not sure if it's the same issue but `fast-glob` 3.2.0 doesn't work with simplest patterns (like a single asterisk) for me. Sorry for spamming but the library is broken at the moment.

**Comment by mrmlnc** [comment]
@ivan-kleshnin, please, file your issue into separated issue. I don't see any problems in addition described in this issue (for limited yarn users).

**Comment by mrmlnc** [comment]
I'm rolled back the `fast-glob@3.2.0` version to `fast-glob@3.1.1`. Wait for the `micromatch` package release.

**Comment by mrmlnc** [comment]
Temporarily fixed on the side of this package.

https://github.com/mrmlnc/fast-glob/releases/tag/3.2.1
