### ISSUE TITLE
Remove a temporary fix for #254

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#256]
#### Source

* https://github.com/mrmlnc/fast-glob/commit/69be6a2c014cf9cafdd750372fec8831c41f3e52
* https://github.com/mrmlnc/fast-glob/commit/f9af59769d555e85b80c46f5838423006e0b5a7d

#### Blockers

* https://github.com/micromatch/micromatch/pull/197

**Comment by devongovett** [comment]
I think switching to picomatch for this has broken some things like brace expansion. I inadvertently upgraded to 3.2.1 via a transitive dependency and things started breaking.

**Comment by mrmlnc** [comment]
Nope, because we [expand brace expansion](https://github.com/mrmlnc/fast-glob/blob/78c7780d78393035db7f3516b04179c7a050fcb8/src/providers/matchers/matcher.ts#L39) previously and… micromatch [call picomatch directly](https://github.com/micromatch/micromatch/blob/0d378e468b2f1c804c76f74ffa097c7d6d1a3bae/index.js#L403).

**Comment by devongovett** [comment]
Sorry, this appears to be a separate issue. https://github.com/mrmlnc/fast-glob/issues/257
