### ISSUE TITLE
unable to use suppressErrors option

### ISSUE THREAD

**Issue by pcrosthwaite** [mrmlnc/fast-glob#269]
### Environment

  * OS Version: Windows 10
  * Node.js Version: 12.16.2
  * Typescript Version: 3.9.2

### Actual behavior
Typescript gives the following error:
Argument of type '{ suppressErrors: boolean; }' is not assignable to parameter of type 'Partial<IOptions<string>>'.
  Object literal may only specify known properties, and 'suppressErrors' does not exist in type 'Partial<IOptions<string>>'.ts(2345)

### Expected behavior
No typescript error

### Code sample

```
fg.sync(`**/*.exe`, {  suppressErrors: true })
```

**Comment by pcrosthwaite** [comment]
Interestingly, if you declare the options as an object, the error doesn't appear
```
const findOptions = {
			onlyFiles: true,
			cwd: basePath,
			absolute: true,
			caseSensitiveMatch: false,
			matchBase: true,
			suppressErrors: true
		}
```

**Comment by mrmlnc** [comment]
Hello, @pcrosthwaite,

Works fine on my machine:

```ts
// typescript@3.9.3
import * as fg from 'fast-glob';

const a = fg(`pattern`, { suppressErrors: true });
const b = fg.sync(`pattern`, { suppressErrors: true });
const c = fg.stream(`pattern`, { suppressErrors: true });
```

Most likely, you are using an outdated version of fast-glob or something is wrong in your environment. Please provide a reproducible/playable environment, for example by creating a repository on GitHub.
