### ISSUE TITLE
How to include the base (root directory) to the results?

### ISSUE THREAD

**Issue by soubhikchatterjee** [mrmlnc/fast-glob#270]
### Environment

  * OS Version: mac os 10.14.6 (18G4032)
  * Node.js Version: v12.4.0

### Actual behavior
If i specify the path _/var/www/html/wallpapers_ it shows the list of files and folder that are inside the  'wallpapers' folder.

### Expected behavior
I want to get the list of files and folder inside the "wallpapers" folder along with the folder "wallpapers" as part of the list.

 

### Code sample

```js
 
  const stream = fg.stream(["/var/www/html/wallpapers"], {
    dot: false,
    onlyFiles: false,
    absolute: false,
    caseSensitiveMatch: false
  });
```

**Comment by mrmlnc** [comment]
Duplicate for #47.
