### ISSUE TITLE
Match failing for some reason

### ISSUE THREAD

**Issue by ihatzi** [mrmlnc/fast-glob#271]
Not sure if I am missing something, but I cant get it to match when a folder has the + sign in it.

**fg.sync(addEsc('D:/Full Base Figure + Morphs & Shells/*', { onlyFiles: true, globstar: true, caseSensitiveMatch: false }));**

I have also tried "**Figure \\+ Morphs & Shells**" and **Figure \\\\+ Morphs & Shells**

All of witch return 0 matches :(

Heeeelp :)

**Comment by ihatzi** [comment]
Also, as an experiment I caned the "+" to a "x" and then it matches, shows that it is the "+" that is causing the issue.

**Comment by mrmlnc** [comment]
Please use issue templates.

1. You cannot use the letter of drive inside the pattern. [Some relevant information](https://github.com/mrmlnc/fast-glob#how-to-use-unc-path). I'll update the documentation to reflect to this restriction. The original `glob` package also does not work.

```js
// You can use the `cwd` option:

glob.sync('*', { cwd: 'D:/' });
// ['Full Base Figure + Morphs & Shells']
```

1. After the first step you can use your pattern:

```js
glob.sync('Full Base Figure + Morphs & Shells/*', {
	cwd: 'D:/'
});

console.log(entries);
// ['Full Base Figure + Morphs & Shells/file.txt']
```
