### ISSUE TITLE
unique option causes static pattern to fail, only when used alongisde dynamic pattern in ava test

### ISSUE THREAD

**Issue by adam-lynch** [mrmlnc/fast-glob#272]
This is a really weird one and I've lost hours trying to figure out what's going on. This is as far as I've narrowed it down but I'm not sure where the actual problem lies

### Environment

  * OS Version: macOS 10.15.2
  * Node.js Version: 12.16.1
  * npm version: 6.13.4
  * fast-glob version: 3.2.2
  * ava version: 3.8.2
  * Reproduce: https://github.com/adam-lynch/ava-fast-glob-issue

### Actual behavior
Only finds one file (`package.json`).

### Expected behavior
Finds two files (`package.json` and `yarn.lock`).

### Steps to reproduce

TL;DR: Follow steps in https://github.com/adam-lynch/ava-fast-glob-issue

_**In an Ava test**_, try to match the following globs in a directory which contains `package.json` and `yarn.lock`:

- `*.txt`
- `package.json`
- `yarn.lock`

### Code sample

See:

1. https://github.com/adam-lynch/ava-fast-glob-issue/blob/master/test/index.js
2. https://github.com/adam-lynch/ava-fast-glob-issue/blob/master/index.js

### Other notes

- If not ran in Ava test, it all works.
- If `unique` is set to `false`, it all works.
- If `*.txt` is removed, it all works.
- There are common dependencies between ava and fast-glob but they all seem to be the exact same version.
- I tried to find any related ava/fast-glob reported issues but had no luck.
- ava issue: https://github.com/avajs/ava/issues/2509

**Comment by mrmlnc** [comment]
Thank you for the detailed description of the issue :tada:

Based on the description, I think it's a duplicate for #268.

**Comment by mrmlnc** [comment]
Shipped with [`3.2.3`](https://github.com/mrmlnc/fast-glob/releases/tag/3.2.3).
