### ISSUE TITLE
How to ignore dot files (directries)

### ISSUE THREAD

**Issue by 345ml** [mrmlnc/fast-glob#280]
I currently have the following use cases in mind
- Get all image files under the home directory.

However, including the dot file would cause performance issues, so I'm trying the following code.

### Environment

  * OS Version: … Debian GNU/Linux 9
  * Node.js Version: … v12.6.0

### Actual behavior
It search the dot directory.
```
Error: EACCES: permission denied, scandir
```

### Expected behavior
The dot directory is not searched.

### Steps to reproduce

  1. Run code.

### Code sample

```js
fg([
  `${userHome}/**/*.jpg`,
  ],
  {
    ignore: [
      `${userHome}/.?*`,
    ]
  }
);
```

**Comment by mrmlnc** [comment]
Hello, @345ml,

The `fast-glob` package does not follow entries that start with the dot by default. You can change this behavior by the [`dot` option](https://github.com/mrmlnc/fast-glob#dot).

Also you can enable the `dot` option and exclude some entries from the search by the [following patterns](https://github.com/mrmlnc/fast-glob#basic-syntax): `/home/mrmlnc/.*`.

**Comment by 345ml** [comment]
@mrmlnc 
Thanks!
I will try!!
