### ISSUE TITLE
copy folder not work on termux

### ISSUE THREAD

**Issue by yozman** [mrmlnc/fast-glob#281]
### Environment

  * OS Version: android with termux app
  * Node.js Version: 14.4.0

### Actual behavior
copy folder is not work

### Expected behavior
…

### Steps to reproduce

1. install termux app on android phone
2. `pkg install nodejs` in termux
3. npm i -g @angular/cli
4. ng new reproduce
5. cd reproduce
6. ng serve

fast-glob use by @angular/cli
configure at angular.json

```json
"assets": [
  "src/favicon.ico",
  "src/assets"
]
```

file type is works well,
folder with glob type will be suspend
so ng serve will waiting for
`92% additional asset processing copy-webpack-plugin`

### Code sample

```js
// Paste your code here.
```

**Comment by mrmlnc** [comment]
Hello, @yozman,

Sorry, I don't know anything about how `@angular/cli` (and `ng`, `copy-webpack-plugin`, …) uses my package. If you can reproduce the problem on your phone directly by working with the `fast-glob` package, please let us know.

**Comment by yozman** [comment]
> Hello, @yozman,
> 
> Sorry, I don't know anything about how `@angular/cli` (and `ng`, `copy-webpack-plugin`, …) uses my package. If you can reproduce the problem on your phone directly by working with the `fast-glob` package, please let us know.

I found the reason.
`os.cpus()` will return `[]` on some platform like android.

**Comment by yozman** [comment]
@mrmlnc 
here is pr to fix it
<https://github.com/mrmlnc/fast-glob/pull/296>
