### ISSUE TITLE
Consider reducing dependencies.

### ISSUE THREAD

**Issue by MicahZoltu** [mrmlnc/fast-glob#284]
`fast-glob` is a pretty popular package that is referenced by a lot of packages all over NPM.  It currently brings in ~16 transitive dependencies to any project that uses it.  As a pretty low-level library, people who use it aren't expecting it is going to bring in a lot of transitive dependencies with it, and it can be surprising to find out that it did.

The two biggest wins would be if `micromatch` and `@nodelib/fs.walk` could get dropped as each brings in 5 transitive dependencies.  I don't know the inner workings of this library so I can't say how easy/hard either of those would be to excise, but it certainly seems like `micromatch` is at least a bit redundant with `picomatch` (already a dependency) and `picomatch` is free of any transitive dependencies.

I acknowledge that this isn't a critical task, but it would be nice if the dependency count went down and I figured it wouldn't hurt to ask.

**Comment by mrmlnc** [comment]
Hello, @MicahZoltu,

I don't see anything wrong with having several lightweight dependencies. I try to keep the package size to a minimum, but I don't want to reinvent the wheel (glob matching, FS walk, queue, merge streams, …).

Some overview:

1. The `@nodelib/fs.walk` package was specifically designed for this package and cannot be removed.
2. The `micromatch` package is one of the fundamental package for a lot of tools. We can't get rid of this package as long as the platform (node.js) does not provide alternative functionality (`picomatch` has no support for [braces](https://github.com/micromatch/picomatch#braces)).
3. The `picomatch` package is a transitive dependency for the `micromatch` package, so, it doesn't cost us anything (thanks to npm dedupe algorithm).

📖 You can use something like [`fdir`](https://github.com/thecodrr/fdir). It has no dependencies, expect `picomatch` if you want to use it as glob library. It is important to understand that this package does not cover many boundary cases that fast-glob handles well.
