### ISSUE TITLE
Ignore doesn't work as expected

### ISSUE THREAD

**Issue by msbit** [mrmlnc/fast-glob#285]
### Environment

  * OS Version: macOS 10.13.6
  * Node.js Version: v14.5.0

### Actual behavior

Files that I would expect to be ignored based on the pattern I have passed in are not.

### Expected behavior

The files are not returned in the output :)

### Steps to reproduce

```
$ cat package.json 
{
  "name": "just-fast-glob",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fast-glob": "^3.2.4"
  }
}
```

```
$ cat index.js 
console.log(require('fast-glob').sync(
  'test/*',
  { ignore: ['*.example'] }
));
```

```
$ find test -type f
test/bar.example
test/foo
```

```
$ node index.js 
[ 'test/bar.example', 'test/foo' ]
```

**Comment by mrmlnc** [comment]
Hello, @msbit,

This is working as intended. We cannot safely handle the case where we need to exclude an entry only at the first level (`*.example`), when the main pattern extends to higher levels (`test/*`).

You can use the following version:

```
test/
  - regular
  - code.example
```

```js
fg.sync('*', {
	ignore: ['*.example'],
	cwd: 'test'
});

// [regular]
```

Also note that this has never worked in the previous versions of `globby` (before switching to `fast-glob`):

```
const fg = require('glob');

const entries = fg.sync('test/*', {
	ignore: ['*.example']
});

// [regular, code.example]
```

```js
const fg = require('globby'); // npm i globby@7.1.1

const entries = fg.sync('test/*', {
	ignore: ['*.example']
});
```

**Comment by msbit** [comment]
Hey @mrmlnc, thanks for the response!

> We cannot safely handle the case where we need to exclude an entry only at the first level (*.example), when the main pattern extends to higher levels (test/*)

I've taken a look through; if I understand this correctly that's due to the `entryFilter` attributes on the options passed to `@nodelib/fs.walk` only operating on the actual entry (without a concept of the origin path of the entry, except for the `path` string attribute).

I've put together a PR for discussion (https://github.com/mrmlnc/fast-glob/pull/286) which, in `getNegativePatternsAsPositive` will add patterns of the form `test/*.example`, looking for any positive patterns ending in `/*`. This seems to work, but let me know what you think about it.
