### ISSUE TITLE
Windows not see path

### ISSUE THREAD

**Issue by Scrum** [mrmlnc/fast-glob#289]
### Environment

  * OS Version: Windows 10.0.17763
  * Node.js Version: v14.8.0

### Actual behavior
`{ entries: [] }`

### Expected behavior
`{ entries: ['D:\\a\\fast-glob-demo\\fast-glob-demo\\test\\fixtures\\index.html'] }`

### Steps to reproduce
see https://github.com/inside-demo/fast-glob-demo/pull/2/checks?check_run_id=1144028881

### Code sample

```js
const path = require('path');
const fg = require('fast-glob');

const input = path.resolve('test/fixtures/index.html'); 
console.log({input})
// => D:\\a\\fast-glob-demo\\fast-glob-demo\\test\\fixtures\\index.html
const entries = fg.sync(input)

console.log({entries})
// => `{ entries: [] }`
```

**Comment by mrmlnc** [comment]
Looks like correct behavior. The `path.resolve` returns a path with backslashes which contradicts with the following rule:

> ⚠️ Always use forward-slashes in glob expressions (patterns and ignore option). Use backslashes for escaping characters.
> https://github.com/mrmlnc/fast-glob#pattern-syntax


Also from FAQ:

https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows

**Comment by Scrum** [comment]
@mrmlnc oh thanks for the hint 🚀
