### ISSUE TITLE
Folder name with brackets will return no results

### ISSUE THREAD

**Issue by Proladon** [mrmlnc/fast-glob#292]
### Environment

  * OS Version: Windows 10 10.0.18362
  * Node.js Version: 14.7.0

  * **I'm using fg in vue-electron**
    * vue/cli: 4.4.6
    * electron: 10.1.0

### Actual behavior
Return empty array if folder name contains brackets.

### Steps to reproduce

  1. Create two folders in desktop and named  each `English`, `English(brackets)` .
  2. past same ones `.jpg` image to each folder.
  2. using `fg()` or `fg.sync()` each other with simple `*` pattern.
  3. `English(brackets)` find nothings, return empty array, but `English` find the .jpg inside, and return an array.

  p.s. This can reproduce whatever folder create anywhere in my pc, if name contains brackets.

### Sample
Create 4 folders in Desktop:
```
C:.
├─English
│  └─67742302_p0_master1200.jpg
│
├─English(brackets)
│  └─67742302_p0_master1200.jpg
│
├─中文
│  └─67742302_p0_master1200.jpg
│
├─中文(括號)
│  └─67742302_p0_master1200.jpg
```

original is html input dragdrop folder function, but simple same as:
```js
// ex. <folder_absPath> : C:/Users/Proladon/Desktop/English/

fg.sync(folder_absPath + '/*', { dot: false })
or
await fg.(folder_absPath + '/*', { dot: false })
```

#### Result: return empty array
![withbrackets (1)](https://user-images.githubusercontent.com/35193493/93862087-20290380-fcf4-11ea-85fb-e19ef59d55b1.gif)

#### Result: return expected
![nobrackets](https://user-images.githubusercontent.com/35193493/93861981-f7a10980-fcf3-11ea-9c9c-5a3781e931fe.gif)

**Comment by mrmlnc** [comment]
Hello, @Proladon,

Looks like a correct behavior due to [this section in FAQ](https://github.com/mrmlnc/fast-glob#why-are-parentheses-match-wrong).

```bash
fg.sync('a/b/**') → ['a/b/file.txt']
fg.sync('a/b(c)/**') → []
fg.sync('a/b\\(c\\)/**') → ['a/b/file.txt']
```
