### ISSUE TITLE
window 7 match all partition file cause error

### ISSUE THREAD

**Issue by zssng** [mrmlnc/fast-glob#293]
### Environment

  * OS Version: windows 7
  * Node.js Version: v12.18.3

### Actual behavior
match `D:\**` cause error:

```
pkg/prelude/bootstrap.js:776
      if (entity[STORE_BLOB] || entity[STORE_CONTENT]) return new Dirent(entry,
1);
                ^

TypeError: Cannot read property '0' of undefined
    at pkg/prelude/bootstrap.js:776:17
    at Array.map (<anonymous>)
    at getFileTypes (pkg/prelude/bootstrap.js:773:20)
    at pkg/prelude/bootstrap.js:864:44
    at pkg/prelude/bootstrap.js:787:9
    at FSReqCallback.oncomplete (fs.js:155:23)
```

I use pkg package app as exe file. which works fine in windows 10.

### Expected behavior
return all file under D:

### Steps to reproduce

  1. …

### Code sample

```js
// Paste your code here.
```

**Comment by mrmlnc** [comment]
Hello, @zssng,

i tried to reproduce the problem as follows:

```js
const fg= require('.');

const entries = fg.sync('**', { cwd: 'D:/', deep: 2, suppressErrors: true });

console.log(entries);
```

Works fine on Windows 10. 

I am not interested in making this package work on legacy operating systems. However, if you want, i'm ready to accept PR.
