### ISSUE TITLE
does not allow wildcards at the root level

### ISSUE THREAD

**Issue by rijnhard** [mrmlnc/fast-glob#294]
### Environment

* OS Version: 
    * CentOS Linux release 7.6.1810 (Core)
    * Linux mint 20 
* Node.js Version: 14.14.0

### Actual behavior
The following returns no matches
`/my_root_*/` 
`/my_root_[[:digit:]]/` 

### Expected behavior
should list
```
/my_root_1/
/my_root_2/
/my_root_3/
```

**Comment by mrmlnc** [comment]
Hello, @rijnhard,

Thanks for the issue!

This issue related to #277 that already fixed by https://github.com/nodelib/nodelib/pull/54, but not available in production.

I will try to release a new version as soon as possible.
