### ISSUE TITLE
Any way to browse multiples dir?

### ISSUE THREAD

**Issue by bacasableio** [mrmlnc/fast-glob#297]
Hello,

I have multiples paths with the same folder structure behind it and I would like to glob all the files in thoses paths.
I tryied the following without success:

` {/path/one,/other/path,/and/another/one}/lodash-mixins/**/*.js`

but it didn't worked as brace only look for next dirs, files.

Is there a way to do this with fast glob?

Regards,

**Comment by mrmlnc** [comment]
Hello, @bacasableio,

Can you give an example of directories? Better in the form of a tree.

The following example shows how you can find all entries with the `.test.ts` suffix in in several basic directories:

```ts
// Multiple patterns
const entries = await fg([
  './packages/first/src/**/*.test.ts',
  './packages/second/src/**/*.test.ts'
]);

// One pattern for two packages
const entries = await fg('./packages/{first,second}/src/**/*.test.ts');

// One pattern for two packages and some service
const entries = await fg('./{packages/{first,second},services/some}/src/**/*.test.ts');
```

**Comment by bacasableio** [comment]
Thank you. 

Didn't know I could pass an array in fg() or fg.sync(). So I did this:
`
const globs = [];
const glob = "lodash-mixins/**/*.js";

loadPaths.forEach(function(loadPath) { // loadPaths look like this ["/srv/framework", "/srv/framework/tests/basic-app/app"]

    globs.push(loadPath + "/" + glob);

});

const results = fg.sync(globs, { unique: true });
`

It worked but in this case unique won't apply accross results. I guess because it just concat results from each glob in my glob array.

> [
'/srv/framework/lodash-mixins/_formats.js',
'/srv/framework/lodash-mixins/_isString.js',
'/srv/framework/lodash-mixins/isDomain.js',
'/srv/framework/lodash-mixins/test.js',
'/srv/framework/tests/basic-app/app/lodash-mixins/test.js'
]

I just wanted to get one test.js here. But it's still great ^^.

Otherwise does files will always be ordered following the array items order from globs?

**Comment by bacasableio** [comment]
Finally I do not need to remove duplicate file.

Anyway here is a short code if someone look to remove file path with same filename from glob results

```
// Returns results without dupes (object mode)
    const objectResults = fg.sync(globs, { objectMode: true }).filter(function(el) {
        if (!this[el.name]) {
            this[el.name] = true;
            return true;
        }
        return false;
    }, Object.create(null));

    // Switch back object as a list
    let arrayResults = objectResults.map(obj => obj.path);
```

 TY for the support.
