### ISSUE TITLE
Surface lstats or isSymbolicLink

### ISSUE THREAD

**Issue by mattriley** [mrmlnc/fast-glob#302]
Hi, this is a feature request. When `followSymbolicLinks` is false, files which are links are not returned. When `followSymbolicLinks` is true, files which are links return the target file stats rather than lstats of the link file. I need to know if I'm dealing with a link, so I'm having to make an extra `lstat` call which doubles the run time. Would it be possible to surface `lstats` or at least a flag to know whether the file is a link? (or is there a way to do this I'm not seeing?) Thanks.

**Comment by ozum** [comment]
In addition to to that, optionally I could have symbolic links only, not their targets.

**Comment by mrmlnc** [comment]
Hello, @mattriley,

Looks like the problem is with the `onlyFiles` option. When is `true` we show only files (not symlinks). When is `false` we show files, directories and symlinks.

```
./issue-302/
├── directory
│   └── file.txt
├── symlink -> ./directory/file.txt
└── symlink2 -> ./directory/
```

```js
fg.sync('./issue-302/**', { onlyFiles: true, followSymbolicLinks: true });
// [
// 	'./issue-302/symlink',
// 	'./issue-302/directory/file.txt',
// 	'./issue-302/symlink2/file.txt'
// ]

fg.sync('./issue-302/**', { onlyFiles: true, followSymbolicLinks: false });
// [ './issue-302/directory/file.txt' ]

fg.sync('./issue-302/**', { onlyFiles: false, followSymbolicLinks: false });
// [
// 	'./issue-302/directory',
// 	'./issue-302/symlink',
// 	'./issue-302/symlink2',
// 	'./issue-302/directory/file.txt'
// ]
```

I think that for convenience we could improve this place in the future, for example, by adding an additional option for detailed control of the results.

Right now you can use the following code sample to display only symbolic links without following them.

```js
const entries = fg.sync('./issue-302/**', {
	stats: true,
	onlyFiles: false,
	followSymbolicLinks: false
});

const result = entries.reduce((collection, entry) => {
	if (entry.dirent.isSymbolicLink()) {
		collection.push(entry);
	}

	return collection;
}, []);

// result → [{ name, path, dirent, stats }, …] where 'stats' point to lstat call
```

**Comment by mattriley** [comment]
Hey @mrmlnc, thanks for the explanation, I am using a similar workaround as you've described. I would look forward to the option of finer grained control.
