### ISSUE TITLE
vulnerabilities

### ISSUE THREAD

**Issue by KMBaby-zyl** [mrmlnc/fast-glob#304]
https://snyk.io/vuln/npm:fast-glob@3.2.5

this package is vulnerability， so it't  not allow to install in my company.

**Comment by mabelleeyanhwa** [comment]
Hi, yes, I can see the vulnerability quite clearly here:
https://snyk.io/test/npm/fast-glob/3.2.5
It is introduced through glob-parent@5.1.1. 

Is this the vulnerability u are referring to?

**Comment by eran10** [comment]
+1

**Comment by mrmlnc** [comment]
Fixed by #315. Will be shipped on this week.
