### ISSUE TITLE
How to match files under special directory with duplicated multiple level path rule

### ISSUE THREAD

**Issue by vimcaw** [mrmlnc/fast-glob#306]
### Environment

  * OS Version: macOS 11.2.2
  * Node.js Version: 15.6.0

### Actual behavior
Can't match the files I want.

### Expected behavior
Match target perfectly.

### Steps to reproduce
For the following files tree:
```
.
├── B
│   └── b1
│       └── test.js
├── a
│   ├── A2
│   │   └── a21
│   │       └── other.js
│   └── a1
│       ├── A12
│       │   └── form.js
│       ├── a11
│       │   └── inner.js
│       └── mid.js
├── c
│   └── cc.js
└── index.js
```
I want to match all files which have a lowercase and numeric name and under a directory of lowercase and numeric name.

The result I want is:
```
a/a1/mid.js
a/a1/a11/inner.js
c/cc.js
index.js
```
In a regular expressions, That is very simple by using `^([a-z0-9]\/?)+.js$`.

But when I try `fg.sync('+(+([a-z0-9])?(/)).js')`, that doesn't work, I think it is because Regex groups doesn't support slash mark.

Is any way to do this in `fast-glob`?

### Code sample

```js
fg.sync('+(+([a-z0-9])?(/)).js');
```

**Comment by mrmlnc** [comment]
You can use a set of patterns to solve this problem. I'm not sure if this is the optimal solution, but it works.

Directories:

```js
index.js

a
a/a1
a/A2
a/a1/a11
a/a1/A12
a/a1/ab0.js
a/a1/mid.js
a/a1/a11/inner.js
a/a1/A12/form.js
a/A2/a21
a/A2/a21/other.js

B
B/b1
B/b1/test.js

c
c/cc.js
c/Q.js
```

Code:

```js
const fg = require('fast-glob');

(async () => {
	const entries = await fg(['**/[[:lower:][:digit:]]*', '!**/[[:upper:]]*/**'], { cwd: './test' });

	console.dir(entries, { colors: true });
})();
```

Result:

```js
[
  'index.js',
  'c/cc.js',
  'a/a1/ab0.js',
  'a/a1/mid.js',
  'a/a1/a11/inner.js'
]
```
