### ISSUE TITLE
"Probably the fastest" - really?

### ISSUE THREAD

**Issue by dandv** [mrmlnc/fast-glob#308]
https://github.com/mrmlnc/fast-glob#highlights says "Fast. Probably the fastest."

But [tiny-glob](https://www.npmjs.com/package/tiny-glob#core-features) says it's 230% faster than fast-glob.

**Comment by mrmlnc** [comment]
Unfortunately, I don't understand what exactly you want to say. We have [benchmarks](https://github.com/mrmlnc/fast-glob#benchmarks) showing that this package is not as fast as written in its description. Both packages have a different set of functionality and bugs.

And, in the best traditions of npm, there is another alternative implementation ([fdir](https://github.com/thecodrr/fdir) that is faster than all the others.

**Comment by dandv** [comment]
Thanks, the link to the benchmarks helped. Would it help to link "probably the fastest" to those benchmarks?

**Comment by trusktr** [comment]
I don't see any benchmarks. For example:

<img width="1236" alt="Screenshot 2024-04-26 at 5 09 10 PM" src="https://github.com/mrmlnc/fast-glob/assets/297678/8ef6d8e3-7326-4140-b8ad-58439efac477">
