### ISSUE TITLE
Ignore patterns not working

### ISSUE THREAD

**Issue by DaanV2** [mrmlnc/fast-glob#313]
### Environment

  * OS Version: Windows
  * Node.js Version: 15.11.0

### Actual behavior

Ignores patterns to be applied on the path.

say you have a project folder: `C:/temp/`
there is a generated folder you try to ignore `C:/temp/OutputFolder`;

then you use fast-glob to retrieve manifest files: `C:/temp/**/manifest.json`
But the `OutputFolder` has been excluded as well

### Expected behavior

that files in the output folder to be excluded

### Note:

I went on a diagnostic step through and found the following:

`convertPatternsToRe` converts the given pattern to: `^(?:OutputFolder[\\\\/])$`

Then in `_filter` (provides/filters/entry) its matches the entire path against negatives patterns such they will always fail

Suggested fix:

micromatch has an option called contains in their option object, it suggested setting this to true for negative patterns

**Comment by mrmlnc** [comment]
Hello, @DaanV2,

Unfortunately, I don't understand your problem, or I can't reproduce it. Please provide the directory structure and the code sample that reproduces the problem.

I tried to reproduce the problem this way:

**Directory structure**

```
C:/fg-test/
├── file.txt
├── OutputFolder
│   └── file.txt
└── SomeDirectory
    └── file.txt
```

**Code sample**

```js
const fg = require('fast-glob');
const glob = require('glob');

const pattern = 'C:/fg-test/**/file.txt';
const ignore = ['C:/fg-test/OutputFolder'];

const entries = fg.sync(pattern, { ignore });
const entries2 = fg.sync(pattern, { ignore: ['C:/fg-test/OutputFolder/**'] });
const entries3 = glob.sync(pattern, { ignore });

console.dir(entries, { colors: true });
console.dir(entries2, { colors: true });
console.dir(entries3, { colors: true });
```

**Results**

To me, the result looks correct. The result does not include files from the excluded directory (`C:/fg-test/OutputFolder`).

```js
// fast-glob
[ 'C:/fg-test/file.txt', 'C:/fg-test/SomeDirectory/file.txt' ]
[ 'C:/fg-test/file.txt', 'C:/fg-test/SomeDirectory/file.txt' ]

// glob
[
  'C:/fg-test/file.txt',
  'C:/fg-test/OutputFolder/file.txt',
  'C:/fg-test/SomeDirectory/file.txt'
]
```
