### ISSUE TITLE
Slow init/require

### ISSUE THREAD

**Issue by chyzwar** [mrmlnc/fast-glob#314]
### Environment

  * OS Version: ubuntu 20.04
  * Node.js Version: 16.0.0

### Actual behavior
```js
var glob = require("fast-glob");
console.log('glob', glob)
```

```sh
$ time node index.js 
glob [AsyncFunction: FastGlob] {
  sync: [Function: sync],
  stream: [Function: stream],
  generateTasks: [Function: generateTasks],
  isDynamicPattern: [Function: isDynamicPattern],
  escapePath: [Function: escapePath]
}

real    0m0,127s
user    0m0,090s
sys     0m0,013s
```
time node index.js

### Expected behavior
Should have similar require time as glob package.
```js
var glob = require("glob");
console.log('glob', glob)
```

```
time node index.js
glob <ref *1> [Function: glob] {
  sync: [Function: globSync] { GlobSync: [Function: GlobSync] },
  GlobSync: [Function: GlobSync],
  glob: [Circular *1],
  hasMagic: [Function (anonymous)],
  Glob: [Function: Glob]
}

real    0m0,082s
user    0m0,065s
sys     0m0,015s
```

### Steps to reproduce
create index.js file and time execution time.
When using fast-glob in cli tools, require/init  time is dominating runtime performance. Only when globing large directories, fast-glob is faster. fast-glob is slower by 50ms when starting process.

**Comment by mrmlnc** [comment]
Some performance optimizations merged into the main branch.

https://github.com/mrmlnc/fast-glob/pull/428
