### ISSUE TITLE
`./` need to ingore

### ISSUE THREAD

**Issue by Rabbitzzc** [mrmlnc/fast-glob#337]
### Environment

  * OS Version: Mac
  * Node.js Version: 14

### Actual behavior
<img width="959" alt="error output" src="https://user-images.githubusercontent.com/26913511/147525471-8858dcc0-1de1-4d8e-8620-441b73333634.png">

### Expected behavior
should output `[index.js, one.md, two.md, three.md]`

### Code sample

```js
const fg = require('fast-glob');

const fn = async () => {
	const entries = await fg(['*', './one.md']);
	console.log(entries);
};

fn();

```

**Comment by mrmlnc** [comment]
This issue is a duplicate for #190.

**Comment by Rabbitzzc** [comment]
ok
