### ISSUE TITLE
Invalid regular expression: /(?<!^)\/{2,}: Invalid group

### ISSUE THREAD

**Issue by cyh41** [mrmlnc/fast-glob#345]
### Environment

  * OS Version:  MacOS 11.6
  * Node.js Version: v16.2.0

**Comment by mrmlnc** [comment]
Thanks for the report. Must be fixed in [`3.2.9`](https://github.com/mrmlnc/fast-glob/releases/tag/3.2.9).

**Comment by cyh41** [comment]
Thanks
