### ISSUE TITLE
`{a,b,c}` no longer considered a dynamic pattern

### ISSUE THREAD

**Issue by amitdahan** [mrmlnc/fast-glob#347]
# Bug Report
Starting with the newly released version `3.2.8` - `{a,b,c}` (sets bigger than 2) is no longer `true` for `isDynamicPattern`, while we only test for `{a,b}` (which still IS considered dynamic).

This broke exactly here:

https://github.com/mrmlnc/fast-glob/pull/344/files#diff-353cf32a130afd9d8b40a67a67f30b51434672caa8ab235726cbd0c82f65fc75R15

### Expected behavior
`isDynamicPattern('{a,b,c}') === true`

**Comment by MurzNN** [comment]
Seems this is not fixed, because I can reproduce this issue with 3.2.10 too, here is my bug report: https://github.com/mrmlnc/fast-glob/issues/351
