### ISSUE TITLE
fast-glob@3.2.7 deleted?

### ISSUE THREAD

**Issue by nsuedu** [mrmlnc/fast-glob#349]
globby@11.1.0
│     └── fast-glob@3.2.7 deduped invalid: "^3.2.9" from node_modules/filemanager-webpack-plugin/node_modules/globby

**Comment by personalZhang** [comment]
+1

**Comment by mrmlnc** [comment]
Nope. 

https://www.npmjs.com/package/fast-glob/v/3.2.7
