### ISSUE TITLE
Can't unignore patterns inside of `ignore` option

### ISSUE THREAD

**Issue by nzakas** [mrmlnc/fast-glob#356]
### Environment

  * OS Version: Windows 10
  * Node.js Version: v16.3.0

### Actual behavior

When specifying the `ignore` option, negated patterns are ignored.

### Expected behavior

When specifying the `ignore` option, negated patterns should be honored.

### Steps to reproduce

  1. Call `fg` or `fg.sync` with an `ignore` option specified containing a negated pattern.
  2. Note that the results do not reflect the negated pattern.

### Code sample

This should return all JS files inside of a directory, ignoring `lib` but including `lib/rules`: 

```js
fg.sync[["**/*.js"], { ignore: ["**/lib/**", "!**/lib/rules/**"] })
```
However, the result is that no files from `lib/rules` are included in the results.

Note: `.gitignore` allows negated patterns such as this to re-include files that were previously ignored.

**Comment by mrmlnc** [comment]
Hello, @nzakas,

Thanks for reporting this issue. Yes, you are right. Right now there is no way to use negative patterns in the `ignore` option to cancel previous patterns.

There is already an issue for this problem — #86. I will close this ticket in favor of the existing one.

**Comment by nzakas** [comment]
Ah thanks! I will follow that one.
