### ISSUE TITLE
[Regression] Ignore group patterns not working

### ISSUE THREAD

**Issue by AgentEnder** [mrmlnc/fast-glob#357]
### Environment

  * OS Version: MacOS
  * Node.js Version: Tested on 12, 14, & 16

### Actual behavior
`**/!(*.ts)` includes typescript files as results

### Expected behavior
`**/!(*.ts)` doesn't include ts files

### More info
This was working in 3.2.7, but broke in 3.2.8. This was discoverred while working on https://github.com/nrwl/nx/issues/9283#issuecomment-1076702800

**Comment by AgentEnder** [comment]
Ok, cool. Thanks for looking into this 🙏.

Should I close out #358, or would it be merged prior to the fix and the test enabled?

**Comment by mrmlnc** [comment]
@AgentEnder, thanks for the reporting issue and test for the regression :tada:.

Fixed in the `master` branch. Will be shipped on monday as `3.2.12`.

**Comment by jeffijoe** [comment]
Hey @mrmlnc! Any estimate on when `3.2.12` will ship? Thanks!
