### ISSUE TITLE
`absolute` option replaces `\` in filename to `/`

### ISSUE THREAD

**Issue by fisker** [mrmlnc/fast-glob#379]
### Environment

  * OS Version: Linux
  * Node.js Version: 18

### Actual behavior

```js
fastGlob('test-a@(\\\\)/test.js')
// -> test-a\/test.js
```

```js
fastGlob('test-a@(\\\\)/test.js', {absolute: true})
// -> /absolute/path/to/test-a//test.js
```

### Expected behavior

should be `/absolute/path/to/test-a\/test.js`

### Code sample

Caused by https://github.com/mrmlnc/fast-glob/blob/a028e3670ba3186a102cb9108e3a6e48c1148a9e/src/providers/transformers/entry.ts#L17 ?

**Comment by mrmlnc** [comment]
Will be included in the `4.0.0` release (#371).

Now, when the `absolute` option is enabled, the path is returned in the OS style.
