### ISSUE TITLE
How much parallelism does this package uses?

### ISSUE THREAD

**Issue by rickmed** [mrmlnc/fast-glob#381]

**Comment by mrmlnc** [comment]
In Node, there are two types of threads: Event Loop (code) and a Thread Pool (fs, dns …). The thread pool size controlled by the `UV_THREADPOOL_SIZE` environment variable. Its default size is 4 ([documentation](http://docs.libuv.org/en/v1.x/threadpool.html)).

Any code can make 4 real concurrent accesses to the file system. The rest of the FS requests will wait in the queue.

But this package also has the [`concurrency`](https://github.com/mrmlnc/fast-glob#concurrency) option. This option allows you to control the number of concurrent accesses to the FS at the package level. By default, this package has a value equal to the number of cores available to the Node process. This allows you to set a value smaller than the pool size (`concurency: 1`) or, conversely, to prepare tasks for the pool queue more quickly (`concurrency: Number.POSITIVE_INFINITY`).

So, in fact, this package can **only make 4 concurrent requests to the FS**. You can increase this value, but in practice it does not give a multiple advantage.
