### ISSUE TITLE
poor performance with large directory in tree (even when ignored)

### ISSUE THREAD

**Issue by ezracelli** [mrmlnc/fast-glob#382]
Hello! I’m using [`yarn@berry`](https://github.com/yarnpkg/berry), which stores dependencies (what would go in `node_modules`) in `.yarn/cache`. Obviously, this directory can get very large. Additionally, [this directory is intended to be committed](https://yarnpkg.com/features/zero-installs#what-does-this-do-to-my-repository-size), meaning the `.git` directory gets large as well.

When executing a glob in my project root, performance is significantly worse when globbing the package root, even with `dot` and/or `ignore` set.

### Environment

  * OS Version: MacOS Ventura (13.2.1)
  * Node.js Version: 18.14.2

### Actual behavior

After a warmup run:

```js
/* ~1.58s */ glob("**/*.(js|ts)", { dot: false })
/* ~1.58s */ glob("**/*.(js|ts)", { ignore: [".git/**", ".yarn/**"] })
/* ~1.58s */ glob("**/*.(js|ts)", { dot: false, ignore: [".git/**", ".yarn/**"] })

/*  ~14ms */ glob("src/**/*.(js|ts)")
```

> See “Code sample” section for full test file

### Expected behavior

The four invocations above should all take approximately the same amount of time.

### Steps to reproduce

  1. Create a directory with a sub-directory (or sub-directories) containing a large number of items (for example, a project using `yarn@berry`)
  2. Execute a glob on the directory

### Code sample

```js
const glob = require("fast-glob");

const createGlobInput = (prefix = "") => {
    return `${prefix}**/*.(js|ts)`;
};

const time = async (input, settings) => {
    const start = performance.now();
    await glob(input, settings);
    console.log(input, settings, performance.now() - start);
};

Promise.all([
    /* ~1.58s */ time(createGlobInput(), { dot: false }),
    /* ~1.58s */ time(createGlobInput(), { ignore: [".git/**", ".yarn/**"] }),
    /* ~1.58s */ time(createGlobInput(), { dot: false, ignore: [".git/**", ".yarn/**"] }),
    /*  ~14ms */ time(createGlobInput("src/"), {}),
]).catch((err) => {
    console.error(err);
    process.exit(1);
});
```

**Comment by GonzaloEsperidioni** [comment]
Same problem! 
Tailwind take a lot of time using patterns like 'node_modules/@my-company/**/*.ts'.
:(

Temp solution: make all absolute path.

**Comment by GonzaloEsperidioni** [comment]
Same problem!
Tailwind takes a lot of time when using patterns like 'node_modules/@my-company/**/*.ts'.
:(

My temporary solution: use absolute paths for all files.

**Comment by mrmlnc** [comment]
Hello,

I do not use yarn in my projects. Could you provide a repository to reproduce the problem?

\\cc @ezracelli @GonzaloEsperidioni

**Comment by ezracelli** [comment]
A great repo to test with would be `yarn@berry`'s repo itself, which has a very large directory at `./.yarn/cache` and (`./.git`, as mentioned): https://github.com/yarnpkg/berry

Note: I no longer have access to the MacOS system mentioned above, and I can't replicate with my current NixOS (Linux) system. Seems like it may be MacOS-specific?

**Comment by mrmlnc** [comment]
I cannot reproduce the problem on my Apple MacBook Pro with M1 Pro or the suggested repository.

```js
$ dua i
Total disk usage: 2.81 GB  Entries: 6680
```

```js
import fg from '../fast-glob/out/index.js';

console.time(`glob`);
const entries = await fg(`**/*.(js|ts)`, { dot: true }); // and false
console.timeEnd(`glob`);

console.dir(entries.length, {colors: true});

// dot: true
time: 21.707ms | Entries: 1024

// dot: false
time: 20.66ms | Entries: 824
```

Well, let's wait for a response from @GonzaloEsperidioni.

**Comment by mrmlnc** [comment]
More details are needed to reproduce the issue. Currently, I believe there is no problem.

**Comment by GonzaloEsperidioni** [comment]
Try this regex `'./node_modules/something/**/src/**/*.{ts,tsx}'` 
it takes a lot of time. 

I could create a repo to test it.
