### ISSUE TITLE
Use `os.availableParallelism` instead of `os.cpus().length` when available

### ISSUE THREAD

**Issue by sapphi-red** [mrmlnc/fast-glob#420]
Now Node.js recommends using `os.availableParallelism` instead of `os.cpus().length` for calculating the amount of parallelism available to an application.
https://nodejs.org/api/os.html#oscpus:~:text=os.cpus().length%20should%20not%20be%20used%20to%20calculate%20the%20amount%20of%20parallelism%20available%20to%20an%20application.%20Use%20os.availableParallelism()%20for%20this%20purpose

The `concurrency` option defaults to `os.cpus().length`. Maybe it's better to use `os.availableParallelism`.
https://github.com/mrmlnc/fast-glob/blob/1b251fad9995e94d57e57ba2582a08c24796e80a/README.md#concurrency
But I'm not sure if `fast-glob` is applicable. Because I suppose the main bottleneck of `fast-glob` would be fs accesses.

**Comment by mrmlnc** [comment]
The `concurrency` option will be removed in the next major version.

In most cases, users do not use this option. There are only a couple of places on GitHub right now where users specify concurrency. The value passed there is `os.cpu().length`.

> In Node, there are [two types of threads][nodejs_thread_pool]: Event Loop (code) and a Thread Pool (fs, dns, …). The thread pool size controlled by the `UV_THREADPOOL_SIZE` environment variable. Its default size is 4 ([documentation][libuv_thread_pool]). The pool is one for all tasks within a single Node process.
> 
> Any code can make 4 real concurrent accesses to the file system. The rest of the FS requests will wait in the queue.
> 
> > :book: Each new instance of FG in the same Node process will use the same Thread pool.
> 
> But this package also has the `concurrency` option. This option allows you to control the number of concurrent accesses to the FS at the package level. By default, this package has a value equal to the number of cores available for the current Node process. This allows you to set a value smaller than the pool size (`concurrency: 1`) or, conversely, to prepare tasks for the pool queue more quickly (`concurrency: Number.POSITIVE_INFINITY`).
> 
> So, in fact, this package can **only make 4 concurrent requests to the FS**. You can increase this value by using an environment variable (`UV_THREADPOOL_SIZE`), but in practice this does not give a multiple advantage.
