### ISSUE TITLE
Merging DEFAULT_FILE_SYSTEM_ADAPTER to fs

### ISSUE THREAD

**Issue by robak86** [mrmlnc/fast-glob#421]
### Environment

  * OS Version: MacOS 13.5.1
  * Node.js Version: v20.3.1

### Actual behavior
The library does not use the exact `fs` object provided in settings. Instead, it composes the final object by merging the original NodeJS implementation with the provided `fs` property. This fails if the provided object's properties are not enumerable, creating unpredictable behaviour. It also makes the library not working correctly with `memfs`.

https://github.com/mrmlnc/fast-glob/blob/a47f97651c5a805abc7c8bccfcc8b0f3ad82c469/src/settings.ts#L211C3-L211C23

### Expected behavior
The library takes the full `fs` (not `Partial`) object as is, leaving merging with the default implementation optional to the user.

### Code sample

```typescript
import { Volume } from 'memfs';
import { glob } from 'fast-glob';

const fs = Volume.fromJSON({
  "/someFile": ""
})

glob.sync("*", { fs });
```
This call uses the original NodeJS `fs` because not all properties from the `Volume` object are enumerable.

**Comment by rondymesquita** [comment]
I'm trying to use memfs as well and not able to mock. All calls goes to real fs package instead. I tried to use `jest.mock('fs', () => ...)` but also no success.

**Comment by mrmlnc** [comment]
After a little investigation, I think it's more beneficial for me to describe this case in the documentation instead of changing the code.

Here's a working example of how you can write a simple adapter:

```js
import { Volume } from 'memfs';
import fg from 'fast-glob';

const fs = Volume.fromJSON({
	'./README.md': '',
	'./src/index.ts': '',
});

const entries = fg.globSync('**', {
	fs: {
		lstat: fs.lstat.bind(fs),
		lstatSync: fs.lstatSync.bind(fs),
		stat: fs.stat.bind(fs),
		statSync: fs.statSync.bind(fs),
		readdir: fs.readdir.bind(fs),
		readdirSync: fs.readdirSync.bind(fs),
	},
});

console.dir(entries, { colors: true, compact: false, depth: 2 });
// README.md
// src/index.ts
```

**Comment by eightHundreds** [comment]
It's not test friendly.
I suspect that the reason why it can't be mocked is because it reads the fs member in advance, which makes it too late for jest.mock to process it.

https://github.com/mrmlnc/fast-glob/blob/master/src/settings.ts#L5-L12

**Comment by mmmmmmmgo** [comment]
> It's not test friendly. 这对测试不友好。 I suspect that the reason why it can't be mocked is because it reads the fs member in advance, which makes it too late for jest.mock to process it.我猜测它无法被模拟的原因是它提前读取了 fs 成员，这使得 jest.mock 来不及处理它。
> 
> https://github.com/mrmlnc/fast-glob/blob/master/src/settings.ts#L5-L12

my solution

```
import fs from 'node:fs'; // the fs will be mock by jest

const globSync = (pattern: string, options?: any) => glob.sync(pattern, { fs: fs, ...options }) as unknown as string[];
```
