### ISSUE TITLE
Regression in v3.3.1

### ISSUE THREAD

**Issue by fisker** [mrmlnc/fast-glob#422]
### Environment

  * OS Version: Linux
  * Node.js Version: 18

### Actual behavior

I have files

```
foo/bar.a
foo\/bar.a
# Note: The second dirname is `foo\`
```

```
> require('fast-glob').sync("foo@(\\\\)/**/{*.a,*.b}")
[] 
> require('fast-glob').sync("foo@(\\\\)/**/*")
[ 'foo\\/bar.a' ]
> require('fast-glob').sync("foo/**/*")
[ 'foo/bar.a' ]
> require('fast-glob').sync("foo/**/{*.a,*.b}")
[ 'foo/bar.a' ]
```

### Expected behavior

Expect

```
require('fast-glob').sync("foo@(\\\\)/**/{*.a,*.b}")
```

to glob `foo\/bar.a` file, and previous version work as expected.

### Steps to reproduce

  N/A

### Code sample

  N/A

**Comment by mrmlnc** [comment]
Fixed in the `main` branch and was backported to `3.x.x`.

**Comment by mrmlnc** [comment]
https://github.com/mrmlnc/fast-glob/releases/tag/3.3.2
