### ISSUE TITLE
Unable to match correctly

### ISSUE THREAD

**Issue by lixiaofa** [mrmlnc/fast-glob#426]
### Environment

  * win11
  * node v18.16.0

### Actual behavior
return []

### Expected behavior
return  [sku.vue]

  

### Code sample

```
import glob from 'fast-glob'
const projectRoot = process.cwd()
const testRoot = path.resolve(projectRoot, 'ssr-testing')
const demoRoot = path.resolve(testRoot, 'cases')
console.log('demoRoot', demoRoot)
    console.log(
      'glob.sync(`${demoRoot}/*.vue`)',
      glob.sync(`${demoRoot}/*.vue`)
    )
```
![image](https://github.com/mrmlnc/fast-glob/assets/23230215/8206504b-0166-4032-a005-679a40ce7ccc)

**Comment by mrmlnc** [comment]
Current behavior is correct.

https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows
