### ISSUE TITLE
No results returned if the file is a socket

### ISSUE THREAD

**Issue by miniBill** [mrmlnc/fast-glob#438]
### Environment

  * OS Version: Linux - NixOS 23.11
  * Node.js Version: v18.19.1

### Actual behavior
```
❯ node
Welcome to Node.js v18.19.1.
Type ".help" for more information.
> const fastglob = await import("fast-glob");
undefined
> await fastglob.default("/run/user/1000/pipewire-0")
[]
❯ ls -l /run/user/1000/pipewire-0
srw-rw-rw- 1 minibill users 0 mar  3 19:02 /run/user/1000/pipewire-0
```

### Expected behavior
The socket file is returned in the result.

**Comment by mrmlnc** [comment]
Hmm. By default, the package returns only files. Literally just files:

https://github.com/mrmlnc/fast-glob/blob/da648078ae87bce81fcd42e64d5b2b1360c47b09/src/providers/filters/entry.ts#L50-L52

Other solutions ([glob](https://www.npmjs.com/package/glob), [wcmatch](https://facelessuser.github.io/wcmatch/)) work differently. They include everything in the results, including sockets, with the option to exclude directories.

I think we should change the current behaviour and start returning everything but directories.

Right now you can disable the `onlyFiles` option.
