### ISSUE TITLE
[QUESTION] - Awilix.fast-glob Fails to Autoload Modules in Tests with TypeScript Setup

### ISSUE THREAD

**Issue by eskylake** [mrmlnc/fast-glob#439]
I know that this may not be an issue and its better to be asked in any stackoverflow-like media.
I already [asked one](https://stackoverflow.com/questions/78333437/awilix-fails-to-autoload-modules-in-vitest-tests-with-typescript-setup).
Also I opened an [issue](https://github.com/jeffijoe/awilix/issues/359) for Awilix recently. Due to the issue I'm asking it in here.

### Environment

  * Node.js Version: node:20.12.2-alpine
 ```json
"typescript": "^5"
"vitest": "^1"
"awilix": "^8"
```

### Actual behavior
As Awilix is using [fast-glob](https://github.com/jeffijoe/awilix/blob/8b3234aeb88e942004adbe48c49d007e37a9775d/package.json#L81), [awilix.loadModules()](https://github.com/jeffijoe/awilix?tab=readme-ov-file#auto-loading-modules) doesn't load modules while creating container through my tests as it doesn't have access to the actual .ts files.
Due to my research, I couldn't find any proper solution to the problem.
I don't wanna use `type: module` in `package.json` & I can't load `.ts` files directly into the container. Also I'm not sure if loading `.ts` files into the container directly is correct.

This won't work:

```typescript
  container.loadModules(
    [
      `${resolve(__dirname, '../*.js')}`,
      `${resolve(__dirname, '../**/*.js')}`,
    ],
    {
      resolverOptions: {
        lifetime: Lifetime.SINGLETON,
        register: asClass,
      },
    },
  );
```

I could fix it by:
1- Including my `test` directory in both `tsconfig.json` and my testing library config (here is my `vitest.config.ts`). But I'm not sure if this is correct. Due to this solution my built version of files are running tests & I believe they are for runtime only.

2- Register each module in the container manually.

```typescript
  container.register({
    MyModule: asClass(MyModuleClass, {
      lifetime: Lifetime.SINGLETON,
    }),
  });
```

### Expected behavior
I expect the provided script auto loads modules located in the paths in both tests and production version:

I have just explained the entire process and all the code snippets related to the problem on [stackoverflow](https://stackoverflow.com/questions/78333437/awilix-fails-to-autoload-modules-in-vitest-tests-with-typescript-setup).

Would you plz help me with this issue?

Thanks in advance

**Comment by mrmlnc** [comment]
I am not sure I can help here. Looks like awilix just call fast-glob without any major options.

Also, I do not use awilix in my applications, preferring to explicitly import dependencies using the DI model from (or like) Nest.js.
