### ISSUE TITLE
(Another) New fast-glob version required due to dependency CVE in micromatch

### ISSUE THREAD

**Issue by lyricnz** [mrmlnc/fast-glob#454]
Similiar to #443 another CVE in micromatch requiring update to micromatch (which isn't available yet?)
See https://github.com/advisories/GHSA-952p-6rrq-rcjv

**Comment by hauserkristof** [comment]
I have opened a PR https://github.com/micromatch/micromatch/pull/266 that fixes the issue in micromatch (https://github.com/micromatch/micromatch/issues/264), wating to be merged.

**Comment by lyricnz** [comment]
micromatch 4.0.7 is not enough to fix tha latest CVE.  Needs 4.0.8

**Comment by 75lb** [comment]
Is this still an issue? When I install fast-glob i get micromatch 4.0.8 and no security warning.. 

```
├─┬ fast-glob@3.3.2
│ ├── @nodelib/fs.stat@2.0.5
│ ├── @nodelib/fs.walk@1.2.8
│ ├── glob-parent@5.1.2
│ ├── merge2@1.4.1
│ └── micromatch@4.0.8
```
