### ISSUE TITLE
Inconsistent behavior around patterns that include `/**`

### ISSUE THREAD

**Issue by SuperchupuDev** [mrmlnc/fast-glob#459]
### Environment

  * OS Version: Windows 10 22H2
  * Node.js Version: 22.8.0

### Actual behavior
`fast-glob` matches `<pattern>` with a `<pattern>/**` pattern only if `<pattern>` is a dynamic pattern (assuming you have `onlyFiles: false` in the options)

### Expected behavior
It behaves the same way regardless of the pattern being dynamic or not

### Steps to reproduce

  1. Create `src/index.ts`
  2. Do `glob('src/**', { onlyFiles: false });`. See how it returns `['src/index.ts']`
  3. Now do `glob('*rc/**', { onlyFiles: false });`. It returns `['src', 'src/index.ts']`

### Code sample

```js
import glob from 'fast-glob';

console.log(await glob('src/**', { onlyFiles: false }));

console.log(await glob('*rc/**', { onlyFiles: false }));
```

**Comment by mrmlnc** [comment]
This is because the `fast-glob` package still does not include the root directory in its output. In the second case, the root directory is considered `.`, so `*rc` matches the `src` directory.

This is a duplicate for #47.
