### ISSUE TITLE
The next performance improvements

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#53]
#### Node.js

  * [x] Use `fs.scandir` from https://github.com/nodejs/node/issues/15699. Most likely it will give double performance increase for work with FS (not on all platforms). Right now I can use the [`scandir-native`](https://github.com/mrmlnc/scandir-native) package, but this is native module and it requires compilation.

#### Algorithm

  * [x] Reduce search time for «constant» patterns (#60).

#### Code

  * [x] Write your own package for recursive directory reading. The `readdir-enhanced` is poorly maintained (code, architecture).

**Comment by mubaidr** [comment]
Regarding the `readdir-enhanced` you can use the default `readdir` and `util.promisify` it.

**Comment by mrmlnc** [comment]
Unfortunately, built-in `fs.readdir` is low level solution. I can write my own solution (and I'll do this as mentioned above), but this will still lead to additional code. We need to be able to understand whether this directory should be read or not (`!**/node_modules`), whether these entries should be filtered or not and etc.

**Comment by mubaidr** [comment]
Good point. 

Also, what do you think adding an option to ignore files listed in `.eslintignore`? But this will require searching or specifying location of eslint ignore file.

**Comment by sindresorhus** [comment]
Relevant: https://twitter.com/bengl/status/1029196268663259136

**Comment by mrmlnc** [comment]
We can also use https://github.com/micromatch/picomatch in the future major release.

**Comment by mrmlnc** [comment]
So, I can close this issue in favor:

* #163
