### ISSUE TITLE
Change double-negative options

### ISSUE THREAD

**Issue by sindresorhus** [mrmlnc/fast-glob#54]
Double-negative options is a bad developer experience. It's better to just invert the default.

`nobrace` => `brace`
`noglobstar` => `globstar`
`noext` => `ext` (Or Maybe even `extension` to be totally clear)
`nocase` => `case`

I realize these are brought over from `node-glob`, but we can do better.

---

[We are now using `fast-glob` in `globby`.](https://github.com/sindresorhus/globby) 😁

**Comment by mrmlnc** [comment]
Hello, @sindresorhus,

Yeap, I agree with you that the current naming has problems. Unfortunately, I use those names as options for «backward» compatibility with `node-glob` and also the same names uses a [`micromatch`](https://github.com/micromatch/micromatch#options).

It seems that we can change this in the next major release.

**Comment by mrmlnc** [comment]
In version `2.1.0` we introduced alternative options for options with the double negation. Please, read https://github.com/mrmlnc/fast-glob/releases/tag/2.1.0 for more details.

 In the next major release, the options with double-negation will be removed.
