### ISSUE TITLE
hope can have depth option

### ISSUE THREAD

**Issue by bluelovers** [mrmlnc/fast-glob#55]
something like

```
a/b/c
d/e/f/g
h
```
with depth 2

will only get
```
a/b
d/e
h
```

**Comment by mrmlnc** [comment]
Hello, @bluelovers,

You can try to use [`deep`](https://github.com/mrmlnc/fast-glob#deep) option. It's work for your case?

**Comment by bluelovers** [comment]
oh sry, didn't see it thx
