### ISSUE TITLE
glob patterns are not working on OSX Yosemite

### ISSUE THREAD

**Issue by alan-agius4** [mrmlnc/fast-glob#6]
Seems like glob patterns are not working on OSX Yosemite
```
node: v6.9.5
npm: 3.10.10
```

such as "**/*.css"

I also download the repo and did `npm test` and they seem to fail as well.
![screen shot 2017-03-11 at 13 24 03](https://cloud.githubusercontent.com/assets/17563226/23823210/09bc9a70-065e-11e7-924c-a21a17e4f0f5.png)

**Comment by alan-agius4** [comment]
The problem seems it is inside one of your dependencies `bash-glob`
https://github.com/jonschlinkert/bash-glob/issues/2

**Comment by mrmlnc** [comment]
Now you can use `bashNative` option with '[]` value.

**Comment by alan-agius4** [comment]
Thanks

**Comment by alan-agius4** [comment]
That will have perf issues in windows though correct?
