### ISSUE TITLE
Doesn't exclude entries when pattern ends with globstar or includes pattern

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#69]
### Environment

  * OS Version: `10.13.3 (macOS)`
  * Node.js Version: `9.5.0`

### Actual behavior

```
['fixtures/directory']
```

### Expected behavior

```
[]
```

### Steps to reproduce

```
fixtures/
├── directory
├── file.md
└── file.txt
```

### Code sample

```js
const entries1 = globby.sync(['fixtures/directory', '!fixtures/**', '!fixtures/directory'], { nodir: false });
const entries2 = fg.sync(['fixtures/directory', '!fixtures/**', '!fixtures/directory'], { onlyFiles: false });

console.log('GLOBBY@7', entries1); // []
console.log('FAST-GLOB@2', entries2); // ['fixtures/directory']
```

**Comment by evilebottnawi** [comment]
@mrmlnc can't adapt in webpack plugin because of this problem :disappointed: Tomorrow i try to adapt `fast-glob` (throw latest `globby`) to `copy-webpack-plugin` (we have a lot of tests) and post issues (if they will be exists :smile: )

**Comment by mrmlnc** [comment]
Sounds bad, but this is just a bug that can be resolved 🎉 

I think that the problem in this line: 

https://github.com/mrmlnc/fast-glob/blob/1b49f50dc723dbe159e8e3896055c1ef4fb680c5/src/providers/filters/entry.ts#L41-L44

And after we can't match the patterns to this path.

https://github.com/mrmlnc/fast-glob/blob/1b49f50dc723dbe159e8e3896055c1ef4fb680c5/src/providers/filters/entry.ts#L56

Maybe we can use additional slash for only condition:

https://github.com/mrmlnc/fast-glob/blob/1b49f50dc723dbe159e8e3896055c1ef4fb680c5/src/providers/filters/entry.ts#L46

Anyway the problem is here :)

Thanks for what you want to use my package :heart: Also I'll be happy to see new issues for bugs 👍
