### ISSUE TITLE
Doesn't work on Windows with absolute paths

### ISSUE THREAD

**Issue by pqvst** [mrmlnc/fast-glob#7]
When I tried to use this on Windows with an absolute path, it appends the cwd to the absolute path

    fastGlob.sync("C:/foo/*.bar");

Causes

    Error: ENOENT: no such file or directory, scandir 'C:\my\current\working\dir\C:\foo'

**Comment by haggholm** [comment]
The same thing appears to happen in OS X. It works fine on my Linux machines, but fails in an analogous fashion on a co-worker’s machine.

**Comment by alan-agius4** [comment]
This is also happening when a pattern doesn't match a file

**Comment by mrmlnc** [comment]
Sorry for delay. I want add some tests and then I'll publish patch-release. Most likely today.
