### ISSUE TITLE
Incorrect deep filtering

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#78]
### Environment

  * OS Version: `10.13.3 (macOS)`
  * Node.js Version: `9.5.0`

### Actual behaviour

Where we set the `cwd` option, the `packages` path is passed to the depth filter and this is matched to the `*` negative pattern. After that, we do not read this directory.

If you pass patterns without `cwd` option (like `app/**/node_modules/**`), then we work with `app/packages` and it's works fine.

```
[]
```

### Expected behaviour

```js
[
  'packages/bar/node_modules',
  'packages/bar/node_modules/baz',
  'packages/bar/node_modules/baz/c.json',
  'packages/bar/node_modules/baz/node_modules',
  'packages/bar/node_modules/baz/node_modules/d.json',
  'packages/bar/node_modules/baz/node_modules/something'
]
```

### Steps to reproduce

```
app
└── packages
    ├── bar
    │   ├── b.json
    │   └── node_modules
    │       └── baz
    │           ├── c.json
    │           └── node_modules
    │               ├── d.json
    │               └── something
    └── foo
        └── a.json
```

### Code sample

```js
const globby = require('globby');
const fg = require('fast-glob');
const fgNext = require('../../OpenSource/fast-glob');

const entries1 = globby.sync(['**/node_modules/**', '!*'], { cwd: 'app', nodir: false });
const entries2 = fg.sync(['**/node_modules/**', '!*'], { cwd: 'app', onlyFiles: false });
const entries3 = fgNext.sync(['**/node_modules/**', '!*'], { cwd: 'app', onlyFiles: false });

console.log('GLOBBY@7', entries1); // Expected behaviour 
console.log('FAST-GLOB@2', entries2); // []
console.log('FAST-GLOB@NEXT', entries3); // []
```

**Comment by mrmlnc** [comment]
I'm not sure that is a bug...

**Comment by jonschlinkert** [comment]
I'm not sure if this is related, but I just found an inconsistency in how node-glob matches paths versus how minimatch matches paths. In node-glob, when a pattern ends with `/**`, it treats the pattern like `{,/**}`. But minimatch (and micromatch, and I believe bash) do not follow that behavior. 

However, it does seem to make more sense in the context of globbing, since the glob is typically matching against the relative part of a (longer) file path.

Maybe try doing something lik this on the pattern before passing it to micromatch. 

```js
if (pattern.slice(-3) === '/**') {
  pattern =  pattern.slice(0, -3) + '{,/**}';
}
```

It might also be worthwhile comparing some tests to output from node-glob. Not that node-glob is always correct, but it might be informative.

**Comment by mrmlnc** [comment]
Hello, @jonschlinkert,

First, thanks you for a great tip.

Unfortunately we cannot use this logic for *negative* patterns, because we can have a broken cases:

```
fixtures/
├── file.md
├── first
│   ├── file.md
│   └── nested
│       ├── directory
│       │   └── file.md
│       └── file.md
└── second
    ├── file.md
    └── nested
        ├── directory
        │   └── file.md
        └── file.md
```

  * Positive: `fixtures/**/nested/**`
  * Negative: `**/nested/**`

We want that

**Comment by mrmlnc** [comment]
Hello, @jonschlinkert,

First, thanks to a great tip. Yeap, it's a good idea, but this does not apply to the current problem.

Unfortunately, this problem also related to issue #80. We exclude directories from reading even if we don't want this. This is related to `deep` filter:

https://github.com/mrmlnc/fast-glob/blob/e09f2d8209fba38fbbbb7ba81f66c8b784b10d20/src/providers/filters/deep.ts#L46

Here we try to exclude the directory from reading using negative patterns. For example, when we provide the `*` as negative pattern – he will be match to `packages` directory. Then we never read `packages` directory.

I want to close this issue in favour of #80.
