### ISSUE TITLE
mock-fs compatibility

### ISSUE THREAD

**Issue by shannonmoeller** [mrmlnc/fast-glob#85]
### Environment

  * OS Version: macOS 10.13.3
  * Node.js Version: 8.9.4

### Actual behavior

I've written a gulp-like file transformer to glob for files, read them, modify them, and write them back to the file system. I've also included delete functionality. As this functionality can be highly dangerous when there's a bug, I test using [`mock-fs`](http://npm.im/mock-fs).

I had been using [`globby`](http://npm.im/globby), but switched to using fast-glob directly. When I was using globby v7 (backed by node-glob) I was able to use mock-fs. Now, using fast-glob, I get ENOENT errors thrown.

### Expected behavior

Allow file-system to be mocked for testing using something like `mock-fs` or by passing a mock file system object to fast-glob as an option.

### Steps to reproduce

  1. git clone https://github.com/shannonmoeller/ygor.git
  2. cd ygor
  3. npm it

### Sample Code

https://github.com/shannonmoeller/ygor/blob/bcf063038fbecb7279468dbd32eecb44322d5e30/packages/files/test/files.js#L12

![image](https://user-images.githubusercontent.com/155164/37248183-e54db0f4-2487-11e8-9718-b25a56c7971d.png)

**Comment by mrmlnc** [comment]
Hello, @shannonmoeller,

Thanks for reporting!

For me this is looks like a bug inside `mock-fs` or `micromatch`. 

An error occurs on this line:

https://github.com/mrmlnc/fast-glob/blob/d9f1ac6f4cb9b5e77086e743fde2413d900583be/src/utils/pattern.ts#L115

I'll invest in it later.

**Comment by jonschlinkert** [comment]
> mock-fs

Given [this](https://github.com/tschaub/mock-fs#upgrading-to-version-4), maybe try using a version of mock-fs before v4 and see if that works. If it does, it seems like something that should be resolved in that package. If not I will update the `use` package in snapdragon 0.8.x, but I'd rather not do that if it's caused by a bug in mock-fs.

**Comment by jonschlinkert** [comment]
nvm, it may well have been a change in mock-fs but I went ahead and bumped the `use` package in snapdragon and published 0.8.2 with that change. You will need to reinstall everything and to make sure NPM uses that version you'll also need to delete package-lock.json files.

**Comment by mrmlnc** [comment]
@jonschlinkert, thanks for the help! I really appreciate it :taco:

We can update the `snapdragon` package to the new version inside `nanomatch`? I've already started doing this. Maybe there's some reason not to do it?

**Comment by shannonmoeller** [comment]
Wow, you guys were _fast_. Thanks!

**Comment by shannonmoeller** [comment]
Confirming this update fixed the issue. Thanks again!

**Comment by jonstuebe** [comment]
Looks like something might have happened again as I'm seeing `ENOENT` errors again.

Using:
`"fast-glob": "^3.2.11"`
`"mock-fs": "^5.1.2"`
