### ISSUE TITLE
Ignore patterns don't work in `ignore` option

### ISSUE THREAD

**Issue by evilebottnawi** [mrmlnc/fast-glob#86]
### Environment

  * OS Version: ubuntu 17.10
  * Node.js Version: latest

### Actual behavior

Ignore patterns don't work in `ignore` option.

### Expected behavior

Ignore patterns should be work in `ignore` option. `node-glob` works perfect.

### Steps to reproduce

  1. Create `file.txt` with any contents.
  2. Create `file.yaml` with any contents.

### Code sample

```js
const fg = require('fast-glob');

fg(['**/*'], {
  absolute: true,
  dot: true,
  ignore: [`!{**/*,*}.txt`],
  onlyFiles: true
})
  .then((entries) => console.log(entries));
```

**Comment by mrmlnc** [comment]
Hello, @evilebottnawi,

You really want to use negative patterns in the `ignore` property? Right now you can use positive patterns instead of negative and it's works fine.

**Comment by evilebottnawi** [comment]
@mrmlnc yes, i have tool which check file contents with extension and report if something wrong, i want get all files exclude some extensions which i don't support. Also `'**/*'` pattern can be configure users (i.e. `images/**/*`).

**Comment by mrmlnc** [comment]
Sounds like feature request.

JFYI: Right now you can use the following work around:

```js
const fg = require('fast-glob');

await fg(['**/*'], {
  absolute: true,
  dot: true,
  ignore: ['{**/*,*}.txt'], // without !
  onlyFiles: true
})
```

**Comment by mrmlnc** [comment]
Just one question:

> Why you use the `{**/*,*}` pattern instead of just a `**/*`?

As I know, `**/*` involve `*` and can be interpreted as «entries with `txt` extension on any nesting level».

**Comment by evilebottnawi** [comment]
@mrmlnc yes, any nesting levels. For me it was breaking change, because `node-glob` support this behavior by default. Workaround glob all files except `*.txt`, i need vice versa logic.

**Comment by reklatsmasters** [comment]
I think this feature related to xojs/xo#65 issue.

**Comment by mrmlnc** [comment]
@reklatsmasters, I think these things are different. Based on the description of this issue – we just want to allow the use `!` in the `ignore` option.

**Comment by evilebottnawi** [comment]
@reklatsmasters @mrmlnc yep, difference

**Comment by evilebottnawi** [comment]
@mrmlnc problem still exists. Example usage `https://github.com/itgalaxy/file-type-lint/blob/master/src/standalone.js#L65`.
`patterns` - `{**/*,*}.*`

**Comment by mrmlnc** [comment]
So, look like misunderstanding in the issue description :)

I just let you use the negative patterns in the `ignore` option.

**Comment by mikehaertl** [comment]
@mrmlnc Are there any news here? This feature would fix a problem with `exclude` option in https://github.com/bmewburn/vscode-intelephense (it uses the `ignore` option of fs-glob).

Use case:

* intelephense should scan all PHP files in a project directory
* it should exclude any `tests` directory below `vendor` it has a default `"**/vendor/**/{Tests,tests}/**",` as `exclude` (=fast-glob `ignore`) option
* it should **not exclude** a specific `**/vendor/abc/tests` directory, so a developer can add `"!**/vendor/abc/tests"` to `exclude`

So the full `ignore` patterns used with fast-glob are:
```
[
  "**/vendor/**/{Tests,tests}/**",
  "!**/vendor/abc/tests"
]
```

Without this feature we'd have to list all `vendor/xyz/tests` directory instead of using `vendor/**/tests`.

**Comment by DaanV2** [comment]
I have some extra information for this problem

Im trying to exclude folder patterns from filepaths using the ignore option.

I have a working folder:

`C:\project\OutputFolder\`

this folder is generated and I wanted to ignore it in my project so I added `OutputFolder` to my ignores.

However, fast-glob did not ignore it.

after a little deep dive I found the following:

`convertPatternsToRe` in `utils/pattern` returns a regex version of the patterns and it got converted to:

`^(?:OutputFolder[\\\/])$`

Meaning it now a regex pattern that tries to match against the entire string to equal to OutputFolder

Line 25 to 26 in `providers/filters/entry.js` tries to math it against the whole path.



Suggested fix.

The library used (micromatch) to convert has an option that can be set, called `contains`

if set to true it will remove the ^ and $ from the regex pattern.
suggestion to set this value to true

**Comment by pbelbin** [comment]
@mrmlnc, I too have a situation where we want to use negative ignore patterns to *allow* certain files to be included in the output, which would otherwise, be excluded due to other ignore patterns.  Would be great to see some progress on this!

**Comment by mrmlnc** [comment]
Another issue about this functionality — #356.

Unfortunately, I could not come up with a decent algorithm that allowed me to implement this functionality without completely rewriting the pattern-matching mechanism when reading in depth.

I will try again later, after the major release of this package. Most likely, it's time to reconsider the approach to how we process patterns in the pattern manager and their further application to directories.

I cannot promise any specific dates.

**Comment by devinrhode2** [comment]
Negated patterns would be really nice for something like this:
```sh
"format:check:ci:non-ts": "yarn prettier --check '**/*.{js,jsx,ts,tsx,mjs,cjs,mts,cts}'"
```

This helps ensure prettier format check is comprehensive, but doesn't repeat what eslint is already doing.
