### ISSUE TITLE
[benchmark] Add tiny-glob

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#97]
So, welcome to the family.

https://github.com/terkelg/tiny-glob

**Comment by mubaidr** [comment]
AFAIK, It is not production ready yet.

**Comment by mrmlnc** [comment]
Blocked by https://github.com/terkelg/tiny-glob/pull/19

**Comment by mubaidr** [comment]
This one too: https://github.com/terkelg/tiny-glob/issues/15

**Comment by mrmlnc** [comment]
Unfortunately, this solution is not ready for use now (just recursive `fs.readdir` with `filter`). Does not run on Windows and does not support `ignore` option.
